### ISSUE TITLE
dwipreproc and mrinfo not reconciled within dev branch

### ISSUE THREAD

**Issue by AlistairPerry** [MRtrix3/mrtrix3#1203] opened 2017-11-30 01:45 UTC
Hello,

I'm running off the development branch in version `3.0_RC2-90-g21f3d913`, to have the `-nthreads` (https://github.com/MRtrix3/mrtrix3/pull/1108) align with the predefined number.

I switched over using the command:

> git checkout remotes/origin/dev

However, I'm running into issues with `dwipreproc`, as it's expecting a different version of `mrinfo`, to what is currently within the branch: 

> mrinfo: [ERROR] unknown option "-json_all"
> dwipreproc: [ERROR] Could not access header information for image 

A quick check of the build logs:

> getting git version in folder "."... 3.0_RC2-90-g21f3d913
 
Cheers,

Alistair

**Comment by jdtournier** [comment] 2017-11-30 13:59
Can you confirm that the `mrinfo` command also returns the matching version (i.e. `mrinfo -version`)? 

Also, to switch over, you should only need to type `git checkout dev` - assuming you haven't set up any other remotes (but that doesn't explain this issue).

**Comment by AlistairPerry** [comment] 2017-12-01 06:41
Issue is still occurring after `git checkout dev`

To confirm the versions which are being run:

> mrinfo
> mrinfo 3.0_RC2-90-g21f3d913 
> 
> dwipreproc
> MRtrix 3.0_RC2-90-g21f3d913

**Comment by jdtournier** [comment] 2017-12-01 10:57
OK, as far as I can tell, the changes you're interested in are only available on `dev` (using final pre-merge commit from #1108):
```ShellSession
$ git branch --contains ff8467c 
  dev
```

yet the version string of your commands (git commit 21f3d913) indicate that you're running a `master` version:
```ShellSession
$ git branch --contains 21f3d913
  master
```
So I'm not sure what the issue is.. Did you invoke `./build` after switching to `dev`...? And made sure that the freshly built executables are in the `PATH`?

**Comment by AlistairPerry** [comment] 2017-12-03 02:44
Hi @jdtournier,

My mistake - I `built` the prior to switching over to the `dev` branch.

All good.

Thanks,

Alistair

**Comment by Lestropie** [comment] 2017-12-03 04:46
We've tried to put checks in place to deal with *MRtrix3* version mismatches, but it's not easy. Trouble here is that the Python scripts report the *MRtrix3* version via a file that is created by the `build` script; hence if you checkout a new branch, then run a script *without* rebuilding the binaries, then both the binaries and the Python script will report the *built* version of *MRtrix3*, rather than the version of the code currently checked out.

To properly detect this error, we'd need to query the *actual* commit currently checked out upon script execution, compare that to the built version of any *MRtrix3* commands executed within the Python libraries, and issue a warning if a mismatch is detected. This could presumably be done with `GitPython`, but I'm not convinced it's worth the additional dependency. Instead we could just call `git rev-parse HEAD` using `subversion`. Possible I think... maybe not top priority though.

**Comment by jdtournier** [comment] 2019-01-30 23:00
I think the original issue is closed? There's now an issue for the version checking (#1527), so I'll close this.

**Closed by jdtournier** 2019-01-30 23:00 UTC
