### ISSUE TITLE
tckglobal Segmentation fault: Invalid memory access in MH Sampler

### ISSUE THREAD

**Issue by LeeReidCSIRO** [MRtrix3/mrtrix3#992] opened 2017-05-17 02:16 UTC
Potentially related to #477 
tckglobal using a HCP dataset is producing segmentation faults.

My call is as follows:
`tckglobal /somepath/diffusion/data.mif /somepath/diffusion/response_wm.txt -riso /somepath/diffusion/response_csf.txt -riso /somepath/diffusion/response_gm.txt -mask /somepath/diffusion/brainmask_diff_space.nii.gz -niter 1e9 -fod /somepath/diffusion/fod_global_tractography.mif -fiso fiso.mif -nthreads 8 /somepath/diffusion/tracks_global_tractography.tck`

The output is as follows:

> tckglobal: [100%] preloading data for "/somepath/diffusion/data.mif"
> tckglobal: [100%] uncompressing image "/somepath/diffusion/brainmask_diff_space.nii.gz"
> tckglobal: [  0%] running MH sampler...
> tckglobal: [SYSTEM FATAL CODE: SIGSEGV (11)] Segmentation fault: Invalid memory access

This 'running MH sampler' can get to anything between 0 - 100% before the crash occurs. In one instance the crash occurred at 100%, and an empty track file had been generated.

**With threading disabled (-nthreads = 0) the issue vanishes.** 

I am happy to supply images and the scripts used to generate them if required.

This is not an issue that is critical for me, as I'm returning to iFod2 for other reasons, but I thought I should flag it for the sake of others.

**Comment by LeeReidCSIRO** [comment] 2017-05-17 02:25
(Upon closer reading I realise that this is highly likely to be the same issue as #477 and so will request 477's reopening)

**Comment by dchristiaens** [comment] 2017-05-24 14:14
To be absolutely clear: this was a new issue, introduced when #785 was merged into `master`. The cause related to memory alignment and the new row method. This is now fixed in #998.

**Closed by dchristiaens** 2017-05-24 14:14 UTC
