### ISSUE TITLE
mrview: popup window with query to save ROI but with only OK button

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#1109] opened 2017-08-31 21:47 UTC
When user creates a ROI in `mrview` and attempts to quit `mrview` without saving ROI, the popup window with notification that ROI has been modified but not saved and question whether user wants to save ROI appears, but there is only one option for user - OK button. When user clicks on OK, ROI is actually NOT saved to file and therefore it is lost.

**Comment by maxpietsch** [comment] 2017-09-01 07:59
I can't reproduce with RC2 on macOS. Can you give us more details? Operating system, MRtrix version, Qt version?

**Comment by ansk** [comment] 2017-09-01 08:15
Here is my specification:
`git describe --tags`
`3.0_RC2-24-gfc18ca9`
Qt version 4.8.6
Debian GNU/Linux 8.3 (jessie)

**Comment by maxpietsch** [comment] 2017-09-02 10:58
Thanks! It's a qt4 vs qt5 issue. Qt5's [QMessageBox::question](https://doc.qt.io/qt-5.6/qmessagebox.html) defaults to yes|no, qt4's version defaults to Ok. We test the return value for `QMessageBox::Yes` which only works for qt5.

The fix is in PR #1111.

**Closed** 2017-09-04 11:18 UTC
Labels: bug, gui
