### ISSUE TITLE
MRview: stack colour bars when multiple bars are present

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#7] opened 2014-05-08 00:13 UTC

**Comment by rtabbara** [comment] 2015-05-20 06:23
Had a go at this. A few points:

* Based off of Dave's suggestion, due to the limited free screen space that might arise from the inclusion of comments/ voxel info. annotations, the colourbars for *all*  tools are located within the same chosen corner (by default this is the top-right, but can be set via the config. parameter <code>MRViewToolsColourBarPosition</code>).

* The collection of these colourbars are laid out as a grid and scaled accordingly, depending on the total number of visible colourbars. The max. number of rows can also be specified via the config. parameter <code>MRViewMaxNumColourBarRows</code>. Additionally, the spacing between horizontally adjacent colourbars can be set via <code>MRViewColourBarHorizontalPadding</code>.

* The rendering of the collection of colourbars should nicely handle hidden items across all the different tools that incorporate colourmaps in some way. So the only real responsibility a user has is to ensure they choose distinct colourmaps for each item to avoid any confusion.

Hopefully that's what people had in mind, but any comments/suggestions would be great.

**Comment by thijsdhollander** [comment] 2015-05-20 06:59
@rtabbara : after pulling in the commit, compilation gives me the following warning:
```
STDERR: [CC] src/gui/mrview/colourmap.o
src/gui/mrview/colourmap.cpp: In member function void MR::GUI::MRView::ColourMap::Renderer::render(const MR::GUI::MRView::Displayable&, bool, float, float, float, float):
src/gui/mrview/colourmap.cpp:268:30: warning: x_offset may be used uninitialized in this function [-Wmaybe-uninitialized]
           data[6] += x_offset; data[7] += y_offset;
```

**Comment by rtabbara** [comment] 2015-05-20 07:10
@thijsdhollander Thanks! Think it should be sorted now.

**Comment by thijsdhollander** [comment] 2015-05-20 07:19
Just tested the actual change itself by adding a ridiculous amount of overlays: seems to work really well in practice!

The default scaling makes them rather tiny when there are 3 rows; but then again, doing otherwise might have them interfere to easily with the main images colour bar at the bottom.  It's always going to be a trade-off of space anyway.  Maybe some users would want them to fill up "columns first" (with a max. number of columns) rather than "rows first" (with a max. number of rows).  But again, that's probably just a matter of individual tastes.  I can't think of any objective arguments for either choice...

I can see scenarios where one would want to show a select subset of the colour bars (now it's all or nothing using the option in the View menu) ... but I see no obvious way of doing this in a convenient and non-messy way in the interface (unless there would be a "show colour bar" in each and every tool that has colour scalable items to overlay; that's maybe a bit too much/messy...?).

**Comment by thijsdhollander** [comment] 2015-05-20 07:37
> unless there would be a "show colour bar" in each and every tool that has colour scalable items to overlay

Heh... okay, ignore that, this option actually is already present... :flushed:

On another note though: when adding an overlay using the RGB or Complex colour map, among other overlays using other colour maps, the colour bar grid still seems to "reserve" a spot for the RGB/Complex colour map's bar... but these colour scales don't have a bar to show.  These "empty bar spots" always show at the bottom of the columns in which they appear (because, I guess, the bars are added additively underneath each other in each column).

**Comment by rtabbara** [comment] 2015-05-21 01:01
@thijsdhollander Thanks for testing it out. After commit 2e7be0f826, laying out of colourbars will ignore any special colourmaps that are used.

**Comment by thijsdhollander** [comment] 2015-05-21 02:02
@rtabbara : it seems to be partially fixed, though I can still get it to behave funky.  Here's an example of how:

1) Open main image, open a single non-DEC overlay: overlay colour bar (defaults to hot scale) shows correctly
2) Open another non-DEC overlay: still correct, shows 2 bars over 2 rows in a 2-row grid
3) Open yet another overlay, but this time a DEC one: still correct, shows 2 bars over 2 rows in a 2-row grid (DEC one is ignored)
4) Open another non-DEC overlay: still correct, shows 3 bars over 3 rows in a 3-row grid -- now correctly still ignoring the DEC one
5) Open another non-DEC overlay: funkyness starts to show, it shows the 4 valid bars *over 2 rows in a 2x2 grid* (or maybe this is a feature... not sure?)
6) Open another non-DEC overlay: funkyness increases, it shows the 5 valid bars over 3 rows in a 3-row 2-column grid.  *The empty spot is in the rightmost column*.  Whereas the previous step might have looked like a feature, this one must've surely not been intended behaviour.. :wink: 

Also, whereas in the first few steps, things appeared to "fill up columns top to bottom", if I give the final result all different colour scales (so I can see which one belongs to which entry in the overlay list), it seems as if they are now in a "fill up rows left to right" kind of ordering... which seems confusing...?

**Comment by thijsdhollander** [comment] 2015-05-21 02:05
...ok, hang on: the above experience also works without step 3... so it doesn't have anything to do with the DEC one.  Adding a bunch more overlays, it seems to me that the current behaviour is to "allocate" extra columns when needed, but the actual fill up order of the grid is over rows.  That makes for a weird sudden reorganisation whenever a column is added, as all bars suddenly jump to entirely new locations...

**Comment by rtabbara** [comment] 2015-05-21 02:22
@thijsdhollander Yep, that was the behaviour I was going for. My thinking was, for example, if you have 4 colourbars, it's more aesthetically pleasing to lay these as a 2x2 grid, rather than having two columns with 1 and 3 colourbars respectively. Maybe see what other people think, but should be an easy enough change either-way.

**Comment by thijsdhollander** [comment] 2015-05-21 02:55
So just to visualize for others, here I start from an anatomical image and progressively overlay FA maps using the colours (in order): red - green - blue - yellow - cyan - magenta - gray scale:
![screenshot0000](https://cloud.githubusercontent.com/assets/11952694/7740587/56fdb60c-ffb7-11e4-9ec1-c52c9d0a2083.png)
![screenshot0001](https://cloud.githubusercontent.com/assets/11952694/7740586/56fd22c8-ffb7-11e4-8be5-dfe9f39894a3.png)
![screenshot0002](https://cloud.githubusercontent.com/assets/11952694/7740589/56ffbc72-ffb7-11e4-9f8d-72ad58546d02.png)
![screenshot0003](https://cloud.githubusercontent.com/assets/11952694/7740588/56fe57b0-ffb7-11e4-84b1-054ed44ac324.png)
![screenshot0004](https://cloud.githubusercontent.com/assets/11952694/7740591/5700fb64-ffb7-11e4-896a-d3b1d5a9d3c3.png)
![screenshot0005](https://cloud.githubusercontent.com/assets/11952694/7740590/57000b6e-ffb7-11e4-9487-73342456acc4.png)
![screenshot0006](https://cloud.githubusercontent.com/assets/11952694/7740592/5724e2a4-ffb7-11e4-9080-163c061f4118.png)
![screenshot0007](https://cloud.githubusercontent.com/assets/11952694/7740593/5725b2b0-ffb7-11e4-9b58-9d38180c5b63.png)

I agree that after adding "yellow", the 2x2 grid is nicer than what might've otherwise been a 3-row column and then a single item column.  But the jump from how it looked before (when blue was added) to after adding yellow is what confused me at that time: my mind had settled on a seemingly top-down strategy of adding (even though it actually is left-right, but over a single column with 3 rows), but suddenly it became left-right.  Also after adding cyan, the layout seems far less optimal than several possible alternatives.  Same thing after adding the final gray scale one (and so on for even more overlays of course).  Whenever you're up to these numbers (anything beyond 3 overlays), switching any of them on/off (even if it's the last one) also causes sudden rearrangements.  I agree, though, that it's impossible (with whatever strategy) to avoid rearrangements whenever switching any overlay on/off if that overlay is not the last one in the "on" list.  The only solution to that would be having "gaps", which is probably not what anyone wants.

**Comment by draffelt** [comment] 2015-06-22 11:32
@jdtournier are you happy with this? so we can close it off.

**Comment by jdtournier** [comment] 2015-06-22 11:41
I think it's definitely good enough to use, and I don't see that we're going to be able to come up with a clean way of laying these out. I think the current approach is the best way to go, at least once you get your head around it, you can easily figure out which colourbar corresponds to which entry in the list, which would otherwise get a bit messy. Happy to close off...

**Closed by jdtournier** 2015-06-22 11:41 UTC
Labels: enhancement, gui, help wanted
