### ISSUE TITLE
mrcalc doesn't handle complex input on Mac

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#430] opened 2015-12-21 11:01 UTC
Just noticed that one mrcalc test fails on my Mac/clang system (in `updated_syntax`):
```
# command: mrcalc mrcalc/in.mif 0+1i -mult -exp mrcalc/in.mif -mult 1.34+5.12i -mult - | testing_diff_data - mrcalc/out4.mif 1.0e-5 [ ERROR ]
mrcalc: [  0%] computing: ((exp ((mrcalc/in.mif * 0)) * mrcalc/in.mif) * 1.34)... mrcalc: [100%] computing: ((exp ((mrcalc/in.mif * 0)) * mrcalc/in.mif) * 1.34)
testing_diff_data: [ERROR] images "/tmp/mrtrix-tmp-aS1shs.mif" and "mrcalc/out4.mif" do not match within specified precision of 1.0000000000000001e-05 (0.450566 vs -0.142684+1.77382i)
testing_diff_data: [ERROR] images "/tmp/mrtrix-tmp-aS1shs.mif" and "mrcalc/out4.mif" do not match within specified precision of 1.0000000000000001e-05 (-1.80695 vs -7.13265+0.240088i)
testing_diff_data: [ERROR] images "/tmp/mrtrix-tmp-aS1shs.mif" and "mrcalc/out4.mif" do not match within specified precision of 1.0000000000000001e-05 (-1.8453 vs -7.27405+0.453556i)
testing_diff_data: [ERROR] images "/tmp/mrtrix-tmp-aS1shs.mif" and "mrcalc/out4.mif" do not match within specified precision of 1.0000000000000001e-05 (0.18633 vs 0.0858523+0.730903i)
testing_diff_data: [ERROR] exception thrown from one or more threads "loop threads"
```
Other tests are fine. Looks like complex numbers are the issue here. When I do
```
mrcalc in.mif 0+1i -mult out.mif
```
the output is 0 and *the datatype is real*. Forcing
```
mrcalc in.mif 0+1i -mult out.mif -datatype cfloat32
```
produces complex output but still 0 as far as I can tell. I get similar output for `master` by the way.

Any ideas?

**Comment by jdtournier** [comment] 2016-01-06 10:13
Strange that this would be an issue on Mac and not other platform... One possibility is that the text conversion for complex numbers isn't working - i.e. `0+1i` isn't being recognised as a complex number, and gets interpreted as a simple zero. This would cause the whole pipeline to default to real since the imaginary part is zero. One way to test this out is to use the command as a simple calculator, and try:
~~~ShellSession
$ mrcalc 1 0+1i -mult
0+1i
$ mrcalc 0 1 -complex
0+1i
~~~
I'd expect the later command to work properly if the issue is with the text parsing, rather than the logic in the rest of the app. Assuming that's the issue, it would also be worth having a look into whether the locale might have an effect here - try setting up your system with a standard US locale, see whether the issue persists.

Interestingly, on my system using `updated_syntax`, these simple commands fails:
~~~ShellSession
$ mrcalc 0+1i
0
$ mrcalc 1i
0
~~~
But they work fine as long as something else happens:
~~~ShellSession
$ mrcalc 0+1i 0 -add
0+1i
$ mrcalc 1i 0 -add
0+1i
~~~
So there clearly is something wrong with the logic here, but it sounds like it's a separate issue...

**Comment by dchristiaens** [comment] 2016-01-06 11:04
It's likely the text parsing indeed:
```
$ mrcalc 1 0+1i -mult
0
$ mrcalc 0 1 -complex
0+1i
$ mrcalc 1 0 1 -complex -mult
0+1i
```
When I run your other examples:
```
$ mrcalc 0+1i
0
$ mrcalc 1i
0
$ mrcalc 0+1i 0 -add
0
$ mrcalc 1i 0 -add
mrcalc: [ERROR] error converting string "1i"
```
This again seems to confirm something's wrong with the text parsing. I tried `setenv LANG en_US.UTF-8 && setenv LC_ALL en_US.UTF-8` but that still gave the same errors.

However, having the `-complex` syntax, the `0+1i` notation is not all that important. I hardly ever use complex types anyhow. Maybe we can just modify the test script to the working syntax and leave it at that?

**Comment by jdtournier** [comment] 2016-01-06 11:10
OK, good to hear. I'd rather figure out why it's getting it wrong on Mac and fix it... It cant' be all that complicated, all the logic for that will happen in [`lib/mrtrix.h`](https://github.com/MRtrix3/mrtrix3/blob/updated_syntax/lib/mrtrix.h#L248-L267)...

**Comment by dchristiaens** [comment] 2016-01-06 13:45
Starting to get a sense of what's happening. Figure this:
```
$ mrcalc 1a 0 -add
mrcalc: [ERROR] error converting string "1a"
$ mrcalc 1b 0 -add
mrcalc: [ERROR] error converting string "1b"
$ mrcalc 1c 0 -add
mrcalc: [ERROR] error converting string "1c"
$ mrcalc 1d 0 -add
mrcalc: [ERROR] error converting string "1d"
$ mrcalc 1e 0 -add
mrcalc: [ERROR] error converting string "1e"
$ mrcalc 1f 0 -add
mrcalc: [ERROR] error converting string "1f"
$ mrcalc 1g 0 -add
1
$ mrcalc 1h 0 -add
1
$ mrcalc 1i 0 -add
mrcalc: [ERROR] error converting string "1i"
$ mrcalc 1j 0 -add
1
$ mrcalc 1k 0 -add
1
$ mrcalc 1l 0 -add
1
$ mrcalc 1m 0 -add
1
$ mrcalc 1n 0 -add
mrcalc: [ERROR] error converting string "1n"
$ mrcalc 1o 0 -add
1
$ mrcalc 1p 0 -add
mrcalc: [ERROR] error converting string "1p"
$ mrcalc 1q 0 -add
1
$ mrcalc 1r 0 -add
1
$ mrcalc 1s 0 -add
1
$ mrcalc 1t 0 -add
1
$ mrcalc 1u 0 -add
1
$ mrcalc 1v 0 -add
1
$ mrcalc 1w 0 -add
1
$ mrcalc 1x 0 -add
mrcalc: [ERROR] error converting string "1x"
$ mrcalc 1y 0 -add
1
$ mrcalc 1z 0 -add
1
```
So it seems like a-f, i, n, p, and x are "forbidden" characters. Luckily, this is a documented (but still unfixed) bug with Clang on Mac OS X. I'm not sure if it also occurs with Clang on other platforms. Official bug report here: https://llvm.org/bugs/show_bug.cgi?id=17782

Just for fun, I modified lines 248-267 to accept the electrical engineers notation 0+1j:
```c++
  template <> inline cfloat to<cfloat> (const std::string& string)
  {
    std::istringstream stream (string);
    float real, imag;
    stream >> real;
    if (stream.fail())
      throw Exception ("error converting string \"" + string + "\"");
    if (stream.eof())
      return cfloat (real, 0.0f);

    if (stream.peek() == 'i' || stream.peek() == 'j')
      return cfloat (0.0f, real);

    stream >> imag;
    if (stream.fail()) 
      return cfloat (real, 0.0f);
    else if (stream.peek() != 'i' && stream.peek() != 'j')
      throw Exception ("error converting string \"" + string + "\"");
    return cfloat (real, imag);
  }
```
With this change, I get:
```
$ mrcalc 1 0+1i -mult
0
$ mrcalc 1 0+1j -mult
0+1i
```
So the good news is there's nothing wrong with the logic of that function or mrcalc. The bad news is that fixing this on Mac requires completely overhauling the implementation of `to<cfloat>(const std::string&)`, to avoid using the `>>` operator of `std::istringstream`.

If you ask me, this isn't worth the trouble, and we better wait for clang to fix this properly. It will take some time though, before such fix would have made it into an update of Xcode etc. What do you think?

**Comment by jdtournier** [comment] 2016-01-06 14:32
OK, I agree, I don't think we should fix things to get around specific compiler bugs in specific versions of specific OS's... We'll wait until Apple decide to fix their compiler. Clearly this is not a problem with clang on Linux (this is what is used in testing), so hopefully the fix will eventually makes its way out into the wild. 

In the meantime, your addition of allowing the 'j' for the imaginary part at least allows correct use of the application, so that's good enough for now. And in any case, there are ways around it using the `-complex` option, and complex numbers are rarely used anyway... Let's close as `wontfix` (although your modification might be considered as fix...?). 

I'll make sure the remaining bug gets filed somewhere too.

**Closed** 2016-01-06 14:32 UTC
Labels: bug, MacOSX, wontfix
