### ISSUE TITLE
'Quieter' command line output

### ISSUE THREAD

**Issue by davesl** [MRtrix3/mrtrix3#161] opened 2015-02-09 16:57 UTC
Hi,

I’ve noticed that the output logs on HPC systems can get quite long during tckgen and tcksift. One of these output logs reached almost 200MB! This is because everything that would normally be printed to the command line is saved in the log.
 
Would it be possible to have an option in addition to -quiet which would only print an update when, say, each percentile is reached? Then only 100 lines would need to be logged instead of some millions!

Cheers,
David

**Comment by jdtournier** [comment] 2015-02-09 17:39
Yes, I've noticed that output files will contain a line for every update of the progress status. This is normally OK for percentage-only output, since the code will only update the status when the percentage value changes. Still, it's probably annoying to see 100 lines of updates...

One idea might be to try to detect whether the command's stderr is connected to a terminal, and modify behaviour accordingly - or just rely on a command-line switch instead. Either way, I'm not convinced that's the best way to deal with this.

What I don't like about this approach is that by preventing status updates at the normal frequency, or worse until processing is done (which would keep your log files nice and lean), you might lose important information as to when exactly a crash or error occurred. It's often quite useful to know how far processing got before crashing out.

Maybe a better approach would be to provide a `-log` option, so the user could specify the name of the log file rather than having to redirect stderr, and we would then have the ability to *seek* within the log file and update the right bits with the expected frequency, while keeping the log file as clean as the output would appear on the command line. 

This would actually be relatively straightforward to implement, by providing alternative handlers for the report_to_user() functions. Only trick is to catch the `-log` option early enough that any other errors would not have occurred *before* these functions have been set... Basically it should be the very first option parsed.

**Comment by Lestropie** [comment] 2015-02-09 23:10
Keep in mind that `tckgen` and `tcksift` don't use `report_to_user_func()`; currently they're direct `fprintf(stderr, ...)` calls, due to requiring the line clear & carriage return characters as well as no automatic newline character.

We could wrap these into a sort of 'manual formatting' progressbar class, then have a command-line option to constrain the outputs. Or probably a simpler option would be to have the default time interval for the IntervalTimer class as a config file option; HPC users could set it to e.g. 1 second or more instead of 1/30th of a second.

None of these will solve the issue with `tcksift` though: in that case we don't actually know for sure when the algorithm will finish, so can't necessarily calculate a percentage, nor are the updates based on a timing interval - it's a line per iteration. But I suspect that this problem would be far worse for `tckgen` than `tcksift`...?

**Comment by jdtournier** [comment] 2015-02-09 23:50
Good points. Just had a quick look through the code: tckgen does use a timer to prevent updates being too frequent. I guess tcksift could use the same approach?

However, it would probably be better to take the approach used in dirgen, which uses a feature I've added to the ProgressBar class: you can update the message during processing. In dirgen, I use it to update the current cost function value. No reason we couldn't use it for tckgen or tcksift too, which I guess would get around these issues...? Bearing in mind that when not in percentage mode, the ProgressBar only updates with an interval timer. This of course assumes that the ProgressBar class's display_func() is also pointing to a modified logging version, which will need to be added as well...

**Comment by jdtournier** [comment] 2015-02-09 23:58
Sorry, just reread your post. I guess my suggestion is essentially what you meant by a 'manual formatting' progressbar class...? Looks like we're on the same page...

Not sure I'd bother changing the time interval between updates for HPC users. It's already long enough not to impact performance, and if we update the log as suggested, it won't make any difference to the output... Besides, I prefer to make sure the logs are as up to date with the processing as possible. I guess 1 second is probably close enough for a long run, as you'd expect to see on a HPC system, but it might be way off for a short run. If it doesn't hurt, I'd just leave it.

**Comment by Lestropie** [comment] 2015-02-09 23:59
Yeah SIFT could potentially use an IntervalTimer to prevent console updates faster than the requested frequency. I'll have a look at the ProgressBar modifications when I get a chance.

Not convinced the log file modification is required: HPC systems with job queueing automatically capture std::cout and std::cerr writes and pipe them to a pair of files without any requirements from the user; it's simply the size of these files that are the problem.

**Comment by jdtournier** [comment] 2015-02-10 00:11
Just noticed the progressbar's set_text() calls the display function, which would bypass the timer mechanism. I'll get rid of that...

And yes, not sure how to handle things if we want to stick with redirection, if that's what HPC users are expecting. Reducing the update frequency is the simplest thing we can do, and maybe we should try to at least detect whether we are running in a TTY and change the interval on that basis. It's not as neat a solution, but I guess if it works...

**Comment by Lestropie** [comment] 2015-02-10 00:17
RE 'manual formatting' progress bar: yes I think we are.

RE time interval: I _think_ we're on different pages here. I think what you're suggesting is that if the piping to a log file is handled by MRtrix, then the line clear / carriage return pair can be replaced with a file truncation and seek, such that the resulting log file only has one line of text for the corresponding progress bar; whereas my suggestion was that if you could reduce the log file size by a factor of 30 or more simply by adding a config file option, that would stop the automatically-generated log files from getting ridiculously large. Yours is neater, mine is easier.

Argh, damn race conditions...

If we went with the log file option, users could specify the log file path, whereas with the systems I've used their names get determined automatically. And the automatically-generated .e / .o files (stderr / stdout captures) would just be empty as everything would have been redirected.

**Comment by jdtournier** [comment] 2015-02-10 15:38
OK, it turns out to be pretty easy to detect when stderr is redirected to file - just need to check whether we can seek over the stderr stream. So I've added functionality to detect this, and if so, terminal text colouring will be disabled, and the output stream update I was talking about above will kick in. This seems to work well on my system - any redirection of stderr to file is now handled much more cleanly, resulting in nice short logs that are nevertheless updated in real time. 

@davesl I'd appreciate if you could checkout the `log_to_file` branch (`git pull & git checkout log_to_file && ./build) and let me know whether that sorts out these issues for you. 

@Lestropie I've had a go at updating `tckgen` and `tckedit` to use the new methods I've added to the ProgressBar. Maybe you could have a go at `tcksift`...? I didn't dare touch it, it's your baby...

**Comment by davesl** [comment] 2015-02-10 18:14
Yes no problem. I'll check the log_to_file version tomorrow and report back.

**Comment by Lestropie** [comment] 2015-02-11 04:17
f8f3cb6a Done.

**Comment by davesl** [comment] 2015-02-11 09:32
I've run a quick test of tckgen using the log_to_file branch. Here's what I'm seeing.

Previously a line was logged after approximately 30 streamlines generated:

5263783 generated,  5172172 selected    [  5%][2K
 5263816 generated,  5172202 selected    [  5%][2K
 5263841 generated,  5172227 selected    [  5%][2K
 5263866 generated,  5172252 selected    [  5%][2K
 5263892 generated,  5172278 selected    [  5%][2K

With the new branch a line is printed for roughly every 500 streamlines generated:

tckgen: [  0%]   453976 generated,   364946 selected
tckgen: [  0%]   454474 generated,   365331 selected
tckgen: [  0%]   454899 generated,   365677 selected
tckgen: [  0%]   455495 generated,   366144 selected
tckgen: [  0%]   455969 generated,   366526 selected

Thus the output logs should now be reduced by a factor of roughly 17.

Is this the type of change you were expecting?

**Comment by jdtournier** [comment] 2015-02-11 09:39
Nope... You should only see one line for the progress report in the log (unless it was interrupted by other messages). I'll take another look...

**Comment by jdtournier** [comment] 2015-02-11 11:08
OK, this works fine on my system. Any chance you could give me more info as to exactly how the command is invoked and how the redirection is actually done? 

Also, maybe you can send me the output log file directly - it's sometimes hard to see exactly what's in there with a simple copy/paste, since whatever program you use to display the text might interpret some of the funny control characters in different ways...

**Comment by davesl** [comment] 2015-02-11 11:28
This is the command I used:

tckgen -seed_image /data/lren/Diff_Tractography/PR00528_RC240885/HARDI/PR00528_RC240885_data_aligned_mask.nii -mask /data/lren/Diff_Tractography/PR00528_RC240885/HARDI/PR00528_RC240885_data_aligned_mask.nii -algorithm iFOD2 -number 50000000 -maxlength 400 -minlength 2 -act /data/lren/Diff_Tractography/PR00528_RC240885/HARDI/PR00528_RC240885_mt_al_mtflash3d_v2l_1mm_ses_01_rep_01_MT_x1000_5TT.nii -backtrack -force /data/lren/Diff_Tractography/PR00528_RC240885/HARDI/PR00528_RC240885_data_aligned_HARDI_fod.nii /data/lren/Diff_Tractography/PR00528_RC240885/HARDI/PR00528_RC240885_data_aligned_HARDI.nii_fod.tck

To submit the job to the HPC system I run a script with the qsub command. I have emailed you the output log file and the job submission script.

Also is there a way to double check that I'm using the correct branch? It seemed to work ok but it might be worth double checking.

Cheers,
Dave

**Comment by jdtournier** [comment] 2015-02-11 12:07
`git branch -vv` will tell you what branch you're sitting on, which remote branch it corresponds to, and whether your branch is ahead or behind the remote branch. For example, my system reports:

    ...
    * log_to_file    f8f3cb6 [github/log_to_file] Update tcksift to use new ProgressBar interface
    ...

which means it's up to date (you'd see additional info in the square brackets if it wasn't up to date). 

I'm trying to figure out how your output came about. If the redirect detection wasn't working, we'd see all the VT100 control codes in there (the `[2K\r`, etc. sequences). We don't, so clearly the system reports that we can seek over the output log file. It looks like in your setup, seek() calls are silently ignored, rather than failing outright. I'm not sure under what circumstances this could happen...

Is there any way you can run the command directly on your system and pipe stderr to file manually? All you need to do is add `2>logfile.txt` to the end of your command. I want to test whether the issue is with your shell's handling of redirection, or whether `qsub` implements its own redirection, which might explain why it's not working...

**Comment by jdtournier** [comment] 2015-02-11 12:17
Other option if you could try it is to add the `2>logfile` in the script file itself, at the end of the `tckgen` command. If that works, we'll know the issue is with the way qsub sets up the redirection. If it doesn't, then that would strongly suggest your system's redirection handling is different from mine, and I'd need to rethink the whole approach...

**Comment by davesl** [comment] 2015-02-11 12:59
I added the 2>logfile  to the end of the command and submitted the job. I've emailed you the outputs.

**Comment by davesl** [comment] 2015-02-11 13:03
Also I checked my git branch and got the same log_to_file information you posted above

**Comment by jdtournier** [comment] 2015-02-11 13:14
OK, it seems to work fine when using manual redirection... Now we just need to figure out how qsub does its redirection - I was thinking they might be using FIFOs, but I just tried it on my system and that causes seek() to fail, and hence MRtrix3 reverts to the normal terminal output - not what you have. Unix pipes behave the same way. Really struggling to see how they could have implemented things...

**Comment by jdtournier** [comment] 2015-02-11 16:03
It looks like I'm not going to be able to figure out how qsub does its redirection any time soon... In the meantime, a simple option for those faced with this issue is to use a command like this one:

    #!/bin/bash
    
    # simply prefix your command with this command to redirect outputs to log files
    # log file prefix will be commandname-PID-date-time.std{out|err}
    
    prefix="$1-${BASHPID}-$(date +'%Y%m%d-%H%M%S')"
    exec "$@" >"${prefix}.stdout" 2>"${prefix}.stderr"

called for example `launch` or `run`, made executable ('chmod a+x launch`), and placed in your PATH. You can then simply run your own command prefixed by `launch` to manually redirect your outputs to appropriately named files (note: not the same convention as qsub to avoid conflicts, uses date/time as well as PID). 

Hopefully that would sufficient for most qsub users...? If so, I'll add a mention of this on the wiki when I have a minute...

**Comment by jdtournier** [comment] 2015-03-12 13:49
@davesl : do the changes in the _log to file_ branch (pull request #181) work for you? If so, I'll merge them in.

**Comment by jdtournier** [comment] 2015-04-24 10:52
Just to update this issue: I've noticed that the changes introduced to deal with this don't work when redirection was performed in append mode, i.e. when running the command like this:

```ShellSession
command >> logfile
```

It correctly detects that output is going to file, and the terminal output functions switch to file handling mode. But seek operations are silently ignored, meaning that progressbar output keeps appending rather than overwriting the previous line. I guess the system prevents seeks to avoid the existing file contents from getting clobbered by the command. This probably explains the issues with qsub discussed above.

Not too sure how to handle this cleanly. I think we _might_ be able to detect when seeks fail, but we still won't be able to keep the output clean. One option that doesn't rely on modifications in MRtrix is to run the commands like this:

```ShellSession
command > tmplogfile; cat tmplogfile >> logfile
```
But this would fail to provide any output if the shell was set to abort on error (`set -e`), since the subsequent `cat` command would never get to run. Conversely, if allowed to run with errors, you wouldn't be able to catch the command's error code, you'd get the (presumably successful) return code of the subsequent `cat` command... Getting this right is doable, but not as trivial as I'd like it to be.

Anyway, I don't think we'll be doing anything further to sort this out, other than maybe documenting this on the wiki...

**Comment by Lestropie** [comment] 2016-06-23 09:25
Re-raised [here](http://community.mrtrix.org/t/mrtrix-redirect-output-and-error-to-a-file/314).

I'm thinking just if `App::stderr_to_file` is true, disable updates through `ProgressBar::update()`, and `ProgressBar::operator++()` _if_ there's no target number. That way, the majority of progressbars based on a 0-100% log will just add 100 lines to the output, which isn't _really_ that bad for the sake of knowing how far something progressed before it crashed in such cases.

**Comment by jdtournier** [comment] 2016-06-23 15:21
@Lestropie: what do you reckon of the approach in #686...?

**Comment by Lestropie** [comment] 2016-08-25 05:06
Closing on account of #686 having been merged.

**Closed by Lestropie** 2016-08-25 05:06 UTC
Labels: enhancement
