### ISSUE TITLE
Use clang-format for C++ code

### ISSUE THREAD

**Issue by daljit46** [MRtrix3/mrtrix3#2643] opened 2023-05-26 10:33 UTC
I would like to suggest to use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to format our C++ code. This will provide consistency and make the formatting of our C++ code uniform for all developers. We can enforce this by a simple CI check that ensures that new codes adhere to our chosen style. clang-format is available on all platforms and is supported by all major IDEs.

As for what formatting style we should use, clang-format provides 6 default styles: LLVM, Google, Chromium, Mozilla, WebKit or Microsoft. We should just pick one and stick with it (you can experiment with the different styles and options [here](https://clang-format-configurator.site/)). If we want to customise specific formatting rules we can, but we should try to stick with one of the defaults.

**Comment by Lestropie** [comment] 2023-05-31 05:52
Personally I'm leaning toward adopting this along with the other software engineering changes, especially post-production-release and given that git blame can be kept clean (#2592) and that changes can be attributed to @MRtrixBot.

Regarding styles:
- Agree that it'd be preferable to avoid custom rules if possible; but depending on how my assessment below goes I might not be happy with any one out of the box...
- Would prefer to avoid due to distinguishing features:
    - Mozilla: Really dislike newline between function return type and name
    - WebKit: Same as Mozilla but also dislike quad spacing
    - Microsoft: Dislike massive vertical spacing caused by dedicated lines for opening brackets
- Regarding the other three: I ran an exemplar .h / .cpp file pair and looked at what it did to my code, and generated the table below. Looks like currently my preference would be LLVM but with a couple of additional constraints. Not guaranteed to be an exhaustive test, would want to re-evaluate with more exemplar code if committing.
- Not a massive fan of column width limit across the board. If I need my code in a narrow column I'll turn on word wrapping... yet looks like all styles default to 80 characters...

--------------------------

| Feature                                                                                | LLVM                   | Chromium               | Google               |
| -------------------------------------------------------------------------------------- | ---------------------- | ---------------------- | -------------------- |
| Forces newline between macro invocation and inputs                                     | No (good)              | Yes (bad)              | Yes (bad)            |
| Short if-statement + operation                                                         | Force two lines (good) | Force two lines (good) | Force one line (bad) |
| Forbids multiple class member variable initialisations on one line                     | No (bad)               | Yes (good)             | Yes (good)           |
| Forbids multiple function arguments on one line if multiple lines                      | No (bad)               | Yes (good)             | No (bad)             |
| Forces reference "&" symbol to be adjacent to variable name rather than typename       | Yes (good)             | No (bad)               | Yes (good)           |
| Indentation of class access modifiers                                                  | None (maybe bad)       | 1 space (maybe good)   | 1 space (maybe good) |
| Spaces between end of code and "//"                                                    | Permit one             | Force two              | Force two            |
| Force double template closing to ">>" rather than "> >" (latter used to be encouraged) | Yes                    | No                     | No                   |
| Forbid empty lines after branch statements                                             | No (good)              | Yes (bad)              | Yes (bad)            |
| Force newline between "throw Exception" and arguments                                  | No (good)              | Yes (bad)              | Yes (bad)            |

**Comment by daljit46** [comment] 2023-05-31 10:11
I'm quite apathetic towards what style we choose as long we choose one and we stick with it. We can customise one of the default presets with a few non-default settings addressing the points in the table above. Ultimately this is just about personal taste.

A more interesting point would be how do we enforce the formatting. There are two options:

1. Require each developer to format their code manually before submitting it. In practice this would result in each developer needing to run `git-clang-format` before they commit their code. Then, a CI check would enforce whether the code has been formatted properly.
2. We can automate the formatting using a [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that is triggered at the pre-commit stage. This would make the formatting step transparent to the developer as it would be applied automatically by git. There are also [tools](https://pre-commit.com/) that can help achieve this.

My preference would be to use the first strategy as I think developers should be aware of how exactly their code is formatted before committing it, but it may be worthwhile investigating the second idea too.

**Comment by Lestropie** [comment] 2023-06-02 01:43
I would prefer 1 also I think. We already have precedent for other types of code checks for which the developer is responsible for making requisite changes to pass CI tests. Also one could set up their IDE to apply formatting at file save. This would make it more likely for the developer to catch cases where the formatter does something they really don't like and would therefore prefer to make some structural change prior to committing.

**Comment by jdtournier** [comment] 2023-06-02 09:03
I reckon if the LLVM style is close enough, let's go with that one. Since we're trying to adopt standard practices, we might as well stick to an established convention, and avoid having to maintain (or indeed, justify) a list of additional constraints. We'll need to adjust our habits a bit, but I reckon it won't take long for us to get used to the minor remaining differences. 

Regarding enforcement, I don't think these are exclusive, right? As far as I understand, there's no way to enforce a client-side pre-commit hook ([there's a note that says these are _not_ copied on clone](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_client_side_hooks)). So we would need to enforce this server side, and that means checking during CI. Even better would have been a [server-side git update hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_update), which would reject pushes until the formatting is correct - but it looks like GitHub doesn't support them (understandably, to be fair). 

But I would like to also have a client-side pre-commit hook to avoid needless format-correction commits. I agree that we don't want the pre-commit hook to make the changes without any input from the user, but there other ways of handling this, e.g. [this one](https://github.com/barisione/clang-format-hooks), which allows you to review the changes `clang-format` would apply before going ahead. Seems pretty good to me...

**Comment by Lestropie** [comment] 2023-06-05 02:11
If the primary issue is "not wanting a large number of commits for which the only purpose is applying code formatting", then we could simply say that we don't want to see such commits and that our CI checks of formatting should pass, and addressing such is up to the developer.

1.  Personally, I would set up my VSCode to apply the corresponding formatting at file save, and so hopefully it would simply never be an issue.
2.  Quite regularly in the past I have reverted a commit, re-generated, and force-pushed to a branch, because I made some silly mistake or omission in a commit, and I'd rather the history be clean. Same logic would apply to code formatting.
    Note that if someone has made a bunch of commits of non-trivial size, and then a few changes need to be made to get formatting to conform, then I've no issue with commits like that cropping up every now and then. It's specifically having formatting commits of comparable frequency and size to actual code changes that needs to be avoided.
3.  If git pre-commit hooks serve the same purpose as 1., then I think it's a viable option. But given the presence of alternatives I don't think it's something that needs to be enforced in any way.

**Comment by daljit46** [comment] 2023-06-05 06:36
> Regarding enforcement, I don't think these are exclusive, right?

Yes, the CI checks will be necessary regardless.

The main benefit of a pre-commit hook would be to provide the developer with an extra utility to check whether their code is formatted. Also using a hook we can ensure that the developer is using the same version of clang-format as the CI (indeed clang-format cannot *always* guarantee that formatting remains consistent between versions, due to bug fixes and minor adjustments).

I have a created a [test repo](https://github.com/daljit46/clang-format-test) that uses [pre-commit](https://pre-commit.com/), which is a very popular framework tool for using already built git hooks, that illustrates the workflow.

**Closed** 2023-08-24 07:37 UTC
