### ISSUE TITLE
Loading a ROI (ROI editor, mrview) crashes

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#396] opened 2015-11-16 00:50 UTC
As originally reported in https://github.com/MRtrix3/mrtrix3/pull/225#issuecomment-153588501 ; only applies to updated syntax branch (I suppose).

**Comment by rtabbara** [comment] 2015-11-16 03:27
Pushed out a fix, but need to check with @Lestropie whether it's indeed to desired behaviour.

**Comment by thijsdhollander** [comment] 2015-11-16 04:00
Just gave it a quick run; at least functionally, it appears to fix the issue!

**Comment by jdtournier** [comment] 2015-11-16 09:30
I'll have to investigate a little here - the fixes shouldn't be needed, everything looks more or less as it should... I'm surprised the ROI is loaded in full after the fix, I'd expect this would skip the 2nd axis? If not, then that's a bug in the `Loop`... And the `std::move (*list[i])` should also work as-is, I suspect the moved object is left in an inconsistent state, causing the crash on destruction. I'll look into it now.

**Comment by jdtournier** [comment] 2015-11-16 11:48
OK, the instantiation of a separate copy of the `Header` to pass to the `ROI_Item` constructor is actually the right thing to do - it ensures the IO handler is not grabbed and held in RAM after the `load()` call, which is what we want - we've loaded all the data onto the 3D texture, we want to close everything off once that's done. 

The changes to the `Loop` are more problematic. There is indeed a bug in there - I'm surprised it hasn't been an issue before, to be honest. The fix works for MRView, but there's lot of failures in the testing. Mind you, pretty much all of these errors are there with or without the fix, so there's something more fundamentally messed up going on here... I'll keep digging.

**Comment by rtabbara** [comment] 2015-11-16 12:53
Thanks for taking a look at it Donald. I had a feeling it was not quite right.

Might help, but can you also check out this line [here](https://github.com/MRtrix3/mrtrix3/blob/updated_syntax/lib/image.h#L327) in <code>image.h</code>?

My understanding is that <code>make_shared</code> will make of a copy of the argument and wrap it in a <code>shared_ptr</code>. But I noticed that the Image class contains some <code>unique_ptr</code> members which will then subsequently be destroyed as a consequence of the copy as they're moved over. So I'm not sure whether that was the intended behaviour?

This does seem strange because at a minimum that would mean that calling <code>get_image</code> twice wouldn't work the second time around?

**Comment by jdtournier** [comment] 2015-11-16 13:48
> My understanding is that make_shared will make of a copy of the argument and wrap it in a shared_ptr. But I noticed that the Image class contains some unique_ptr members which will then subsequently be destroyed as a consequence of the copy as they're moved over. So I'm not sure whether that was the intended behaviour?

Not quite. The `Image` class itself contains no `unique_ptr` members - only the stuff necessary to index the image and access the `Buffer` ([these are the only members](https://github.com/MRtrix3/mrtrix3/blob/updated_syntax/lib/image.h#L176-L184)). It does have a `shared_ptr` to the internal `Buffer` class, which is essentially a `Header` with additional datatype-specific methods to handle access to the image data. This `Buffer` class does contain a `unique_ptr` to a RAM buffer, which if set points to the data loaded from or to be written back to the image (in those cases where a preload or explicit write-back is needed). 

So upon copy, only the members of the `Image` get copied, including the `shared_ptr` to the `Buffer`. The `Buffer` itself doesn't get copy-constructed at this point, so all should be well.

> This does seem strange because at a minimum that would mean that calling get_image twice wouldn't work the second time around?

Yes, I don't think I've actually documented that anywhere yet, but that is the expected behaviour. Originally, the `Header` owns the IO handler. When `get_image()` is called, this is _moved_ over to the image's `Buffer`, so the resulting `Image` (and any copies thereof) owns the IO handler - it is explicitly stripped out from the original `Header`, so that calling `get_image()` again will fail. This is very much intentional - I designed things that way to ensure that ownership of the structures managing data is very clearly defined. 

The problem here is that now that the `Image` can be standalone, it includes a reference to its own version of the `Header` (i.e. the `Buffer`). So once constructed from a `Header`, there is the possibility of two independent structures both mapping onto the same data (i.e. both the original `Header` and the `Image`'s newly-created internal `Buffer` refer to the same IO handler). If you then go on to modify the `Header` in some way, there is a chance that will mess things up for the `Image`. One very obvious problem otherwise is that destruction of the IO handler might happen at the wrong time if both structures are allowed to keep references to it. So the approach here is very much along the lines of the gymnastics performed by `unique_ptr` and particularly its previous `auto_ptr` version, which have very strict ownership rules and semantics to ensure only one instance has ownership at any one time. 

Does this make sense?

**Comment by jdtournier** [comment] 2015-11-16 15:02
OK, fixed the issue with the `Loop`, and also fixed a couple of other bugs that were causing failures in testing (unrelated to current issue). There are still a few tests failing, but they're related to the fixel commands, which I'm not so familiar with. Otherwise transformcalc is still failing, not sure why - haven't looked into it... Maybe because there's been a fix on `master` that hasn't been replicated on `updated_syntax`...?

Current issue seems fixed - at least at my end. Closing for now, feel free to re-open if there is the slightest hint that the problem remains...

**Comment by rtabbara** [comment] 2015-11-16 22:53
@jdtournier Thanks for the fix!

<blockquote>
 If you then go on to modify the Header in some way, there is a chance that will mess things up for the Image.
</blockquote>

This makes sense. The problem is that just looking at how <code>get_image()</code> is used, particularly within MRView, I don't think it's then used correctly.

For a few of the tools, it seems that we're calling <code>get_image()</code> on all headers in the list *every-time*  we add a new image to load. In practice, this probably doesn't make much of a difference for most of the tools, although it might have implications for the ROI tool given that it's one of the few tools that also can write to disk?

I think if it was the case that once <code>get_image()</code> is called, we could prevent the use of the original header reference that could potentially be safer (?). But I'm sure how one could do that cleanly, and I think you're probably suffering from refactoring fatigue so I'm not going to push for it.

**Comment by jdtournier** [comment] 2015-11-16 23:43
> The problem is that just looking at how get_image() is used, particularly
within MRView, I don't think it's then used correctly.

Not sure I know what the problem is. Can you point out any particular
examples of that?

> For a few of the tools, it seems that we're calling get_image() on all
headers in the list every-time we add a new image to load.

I'm not following... This seems like the right thing to do, maybe I'm
missing something? The file chooser returns a list of filenames, so we go
through the list to load each one in turn. But the overlay and odf tools
don't seem to call `get_image()` at all - they just open the header and
pass that onto to the `MRView::Image` constructor, which takes care of the
rest. The ROI tool is particular in that it doesn't maintain an active
`Image`, it loads the data directly onto the GPU, and dumps the
Header/Image afterwards.

> In practice, this probably doesn't make much of a difference for most of
the tools, although it might have implications for the ROI tool given that
it's one of the few tools that also can write to disk?

Like I mentioned above, the ROI tool doesn't actually keep an active Image
or Header. When it saves, it creates a new one for the output image, copies
the data from GPU into it, and that's all - that `Image` was temporary, it
disappears once it goes out of scope, having written out the data. Is this
what you might have been wondering about?

> I think if it was the case that once get_image() is called, we could
prevent the use of the original header reference that could potentially be
safer (?). But I'm sure how one could do that cleanly, and I think you're
probably suffering from refactoring fatigue so I'm not going to push for it.

Not sure what you're saying here... To me, that sounds more or less like
what the implementation does anyway - you can't use the Header to access
the same image after the first `get_image()` call, its IO handler will be
null (none of the other members are shared, so there's no scope for issues
there). You can still use the Header as a template for a `create()` or
`scratch()` call, mind you. Other issue is that you can modify the Header
between an `open()`, `create()` or `scratch()` call (Header version) and
the subsequent `get_image()` call. I tried to put safeguards in place to
prevent that, but they were unwieldy and ended up just getting in the
way... Ultimately, it should be obvious to developers that doing this would
be a bad idea.

Not sure I've answered the right questions...(?) Feel free to tell me if
I'm wide of the mark...

**Comment by jdtournier** [comment] 2016-02-08 12:09
Seems this is still a problem on `updated_syntax`... On my system, it bails out with a failed assert:
~~~ShellSession
mrview: ./lib/image.h:353: MR::Image<ValueType> MR::Header::get_image(bool) [with ValueType = bool]: Assertion `valid()' failed.
~~~
This really would best be fixed before we merge...

**Comment by maxpietsch** [comment] 2016-02-08 16:38
I'll give it a go to fix the ROI issue tonight or tomorrow.

**Comment by jdtournier** [comment] 2016-02-08 20:01
:+1:

**Comment by maxpietsch** [comment] 2016-02-09 10:44
f182b08 should fix the ROI loading.

**Closed** 2016-02-09 10:47 UTC
Labels: bug, critical
