### ISSUE TITLE
population_template: Investigate changes in output

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1676] opened 2019-08-13 05:12 UTC
As reported in #1614.

The output of this script seems to differ by quite substantially more than expected between `master` and `dev`. This warrants further investigation.

**Comment by thijsdhollander** [comment] 2019-08-13 07:22
Alright, can confirm `population_template` on `dev` is broken: between the linear iterations, `linear_templateXX.mif` jumps back and forth every other iteration.  The initial template (before the linear iterations) looks far sharper and better than all subsequent ones.  Not sure when what got broken, but my first guess would be either something `mrgrid` related, or something matrix module related (for no particular reason other than being 2 relatively major changed things upon which `population_template` depends).  But whatever it is, it's something that's playing out at the very least at a stage before `linear_template0.mif` is generated; that might help narrow it down.

**Comment by maxpietsch** [comment] 2019-08-13 12:54
`matrix.dot(matrix.load_transform('a.txt'), matrix.load_transform('b.txt'))` gives the wrong result, `matrix.dot(matrix.load_matrix('a.txt'), matrix.load_matrix('b.txt'))` is correct. 

Can we get rid of `data = data[0:3]` in `matrix.load_transform`? We should also add a check for dimension mismatch in `matrix.dot`.

**Comment by thijsdhollander** [comment] 2019-08-14 05:59
> matrix.dot(matrix.load_transform('a.txt'), matrix.load_transform('b.txt')) gives the wrong result, matrix.dot(matrix.load_matrix('a.txt'), matrix.load_matrix('b.txt')) is correct.

Yeah, that seems to check out indeed.

> Can we get rid of data = data[0:3] in matrix.load_transform? We should also add a check for dimension mismatch in matrix.dot.

Rob, what's the intention of that `data = data[0:3]` line? I might be missing something, but it seems (to me) that that should never be required?  Some edge case or special scenario that we / I are overlooking?

There's a similar kind of line that might not be required (unless overlooking things), and maybe cause similar issues if encountered, i.e. in `load_vector` the `return data[0]`.  This would probably then have to be changed to simply `return data`...?

> We should also add a check for dimension mismatch in matrix.dot.

A good safety measure in any case.

**Comment by thijsdhollander** [comment] 2019-08-14 06:56
In the meantime, I can confirm with relatively high certainty that the `load_transform` is the *only* issue.

**Comment by Lestropie** [comment] 2019-08-14 10:05
Okay, the issue was that at the time I had wanted to store affine transform data internally as 3x4; but it never registered that this would be incompatible with a matrix dot product. :man_facepalming:  2a97a30 passes tests comparing to the test data that were generated on `master`.

**Comment by Lestropie** [comment] 2019-08-14 10:24
Correction: I'd had to re-generate the test data at some point using `dev`. There was in fact a more subtle change in output between `master` and `dev` that I was thinking of; the `matrix` module issue described above was a more egregious divergence over and above that, but there definitely still is a difference in `population_template` output between `master` and `dev` (and that difference is over and above the fact that #1609 results in the FoV being 2 voxels smaller in each spatial dimension).

**Comment by maxpietsch** [comment] 2019-08-14 10:40
Does the output of `dev` look worse or wrong? Debugging and comparing master and dev is a nightmare for `population_template` given the history of changes to the script syntax, variable names and the number of moving parts involved.

**Comment by Lestropie** [comment] 2019-08-14 10:45
I've only observed it in the process of #1614, which uses 5mm voxel test data, so can't assess quality from that. Agree that the diff will be a nightmare; was thinking of compiling & running for some higher-resolution test data for a bunch of PR merge commit hashes, try to isolate the relevant changeset that way.

**Comment by Lestropie** [comment] 2019-08-14 10:55
Looks like the difference in `population_template` output may be way smaller than the difference between the old `dwiintensitynorm` and new `dwinormalise group`. Let me stuff around with it a little more before I defer too much.

**Comment by Lestropie** [comment] 2019-08-14 12:44
Okay, traced:

1. Baseline is first commit prior to #1609. Observation regarding template mask images during non-linear registration is that the number of voxels basically stabilises after the first iteration.

2. Using result of merge of #1609, the template appears to be "shrinking" around the periphery. Number of voxels in template masks continually decreases between non-linear iterations.

3. Using same commit as 2., except modifying `population_template` to use the old `mrcrop` command instead of `mrgrid crop` in two locations. Behaviour reverts to that of 1.

So the observed effect appears to be manifesting from the difference in behaviour between `mrcrop` and `mrgrid crop`. The one difference I am aware of is that `mrcrop` used to provide one voxel of padding around the provided mask, rather than cropping tightly to the mask. The logic here was that even for those voxels at the outer edge of a mask image, interpolation on the mask (& any other associated image on the same grid) may still yield "acceptable" image values beyond the centre of that outermost voxel. There I was thinking more about streamlines data, but clearly it seems to be having an effect for template generation.

Rather than reverting the behaviour of `mrgrid crop`, it may instead be preferable to either add a `maskfilter dilate` step prior to `mrgrid crop`, or pipe the output of `mrgrid crop` to `mrgrid pad`.

Thoughts?

**Comment by thijsdhollander** [comment] 2019-08-15 08:53
> Rather than reverting the behaviour of mrgrid crop, it may instead be preferable to either add a maskfilter dilate step prior to mrgrid crop, or pipe the output of mrgrid crop to mrgrid pad.

I have the feeling you're going to see this kind of change, or answer to questions or problems, etc... pop up in different places though; I mean, it might be that the `maskfilter dilate` step prior to `mrgrid crop` is or will be the more common scenario.  So well, I think it's maybe not a bad idea to consider reverting the behaviour of `mrgrid crop`.

By the way, seeing that this bit is what the difference here comes down to, does indeed perfectly logically explain the iterative shrinking behaviour you're seeing; so that checks out for sure.

**Comment by maxpietsch** [comment] 2019-08-15 10:47
Thanks for tracking that down, Rob!

> I mean, it might be that the maskfilter dilate step prior to mrgrid crop is or will be the more common scenario.

I can't think of a use case where that might be the case other than in `population_template`. The 
`mrgrid crop -mask` description is explicit about this change and how to revert to the old behaviour so I don't think that'll be an issue.

> Rather than reverting the behaviour of mrgrid crop, it may instead be preferable to either add a maskfilter dilate step prior to mrgrid crop, or pipe the output of mrgrid crop to mrgrid pad.

Dilating the mask before cropping is preferable as zero-padding the images can introduce large image intensity gradients for the outer most voxels. PR in #1678.

**Comment by thijsdhollander** [comment] 2019-08-15 22:35
>  can't think of a use case where that might be the case other than in population_template. The
mrgrid crop -mask description is explicit about this change and how to revert to the old behaviour so I don't think that'll be an issue.

Only ever other case where users want to be able to interpolate their data properly at the edge of the mask after cropping. As the cropping is typically used for huge high resolution datasets for obvious reasons, it's already quite an undertaking and whatever that processing is will take time and generally be quite heavy. Then discovering that they're not able to do something they want to do means having to go all the way back and causing a lot of frustration.  I've seen this exact scenario play out already once very very recently with someone using the latest version of the code there.  Entirely your choice though; the above just so you know.  Not going to argue further; you've got all the info.

**Comment by maxpietsch** [comment] 2019-08-16 09:29
Ok, I think I see what the issue is: Interpolation can change from linear or whatever specified to nearest at the edge of the FOV when transforming a tightly cropped image which results in visible staircase patterns at the transition from inside to outside the mask. Happy to revert to padding the cropped image by 1 voxel.

The same problem occurs if the brain touches the edge of the FOV. We could change the image interpolation to always pad with 0s at the edge of the FOV but I think that's not a trivial change and a source of potential bias so we'd still need to pad the mask before cropping unless we merged mrtransform and mrgrid 👀. 

@Lestropie Shall I add an option to mrgrid that lets the user control the mask crop margin?

**Comment by Lestropie** [comment] 2019-08-16 09:52
> Shall I add an option to mrgrid that lets the user control the mask crop margin?

Yea that's what I was thinking. The question then becomes what the default should be. Keeping it consistent with the old `mrcrop` probably makes sense given changing from 1 voxel to 0 is known to cause issues in some circumstances.

**Closed** 2020-04-22 18:03 UTC
Labels: help wanted, scripts
