### ISSUE TITLE
tcknormalise (tcktransform?) randomly changes order of streamlines when multi-threading

### ISSUE THREAD

**Issue by giulia-berto** [MRtrix3/mrtrix3#1576] opened 2019-03-08 08:56 UTC
When using multi-threading to warp a .tck file with tcknormalise, the order of the streamlines is not preserved. On the contrary, when using single-thread, the order is preserved. In some cases this may be a problem, e.g. when dealing with labelled streamlines such as during segmentation. As evidence of this behavior, I attach two plots showing the distribution of the distance of corresponding streamlines before and after the warp with (i) single thread and (ii) multi-thread. With single thread, the mean is plausibly centered around 4 mm, instead with multi-threading it is centered around 60 mm, meaning there is no more correspondence between streamlines after the transformation. 

![hist_single_thread](https://user-images.githubusercontent.com/20837136/54017702-1a59e480-4187-11e9-8d00-94bc6566f416.png)

![hist_multi_threads](https://user-images.githubusercontent.com/20837136/54017714-26de3d00-4187-11e9-866c-cd6dd47b3fb9.png)

This problem may affect the new tcktransform too.

Could you please fix the issue?

**Comment by Lestropie** [comment] 2019-03-08 09:04
Hi @giulia-berto,

The issue is described in #502, and has very recently been re-raised in #1571. I mentioned in my comments in #1571 that while there's an entry in the Description section of the help page of relevant commands that this behaviour occurs, it's far from guaranteed that any particular user will see it. 

Since this is the second time in short succession that the limitation has been described, I've elevated #502 to be a part of the RC4 tag update that's currently being worked on.

Cheers
Rob

**Comment by giulia-berto** [comment] 2019-03-08 09:13
Great, thank you! 

Best,
Giulia

**Comment by Lestropie** [comment] 2019-04-02 23:55
Closing as effectively a duplicate of #502; being addressed in #1589.

**Closed by Lestropie** 2019-04-02 23:55 UTC
Labels: duplicate
