### ISSUE TITLE
Sparse (fixel) image opened as main image in MRview

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#276] opened 2015-06-22 07:12 UTC
So I accidentally mistyped/auto-completed at the command line and opened a sparse (fixel) image in MRview, as the main image.  This is what it looks like:

![fixels-as-main-image](https://cloud.githubusercontent.com/assets/11952694/8276586/a348f5be-18fb-11e5-948f-0e7a09885cc1.png)

I'm pretty sure the sparse images weren't supposed to (be able to) be opened in the viewer as a main image; but it does seem to *allow* it, even through the gui itself.  No errors/crashes whatsoever, but as you can see, the current result is probably not intended as well (but does preserve some spatial information; probably just enough to confuse some unsuspecting users big time).

Whereas my first reaction was along the lines of "opening sparse fixel images as the main image shouldn't be allowed", it did get me thinking: could there be a sensible way to allow showing these sparse images as a scalar map anyway?  Maybe just the sum of the fixel values (in the most prevalent use case these should be integrals?) for each voxel?  The voxel information (bottom left) could even enlist (all) the separate values in that case.  Or would it be better to simply forbid opening them as main images after all?

**Comment by Lestropie** [comment] 2015-06-22 07:46
I lost this argument the first time around...

The values you're looking at there are actually offset pointers to the sparse data. Having those stored as a standard 3D image makes the programming interface consistent with standard images; navigating around is the same, it's only when you call the value() function that instead of a scalar value, you get an interface for accessing the individual fixels in that voxel.

Whether it should be possible to open such images in the viewer (or as an image input in any other command, for that matter): well, the data is there, and it can be seen, or even processed using e.g. mrcalc, even though that'd be entirely daft. At least the result of any processing would _not_ be written as a sparse image, so won't cause segmentation issues. But to prevent the user from doing so would only be restriction for the sake of restriction, which we generally try to avoid; nothing here is 'broken' _per se_.

I'm most definitely against displaying any fixel statistics by default in the viewer. Not only would it require nightmarish code branching, it's ambiguous as to exactly what statistic across the fixels should be displayed (i.e. sum, mean, count, ...); that's exactly what the `fixel2voxel` command is there for. We can't display the 'most probable' use case (hiding processing / data from the user while doing so) as it may have no reasonable interpretation in another use case; and once you start adding GUI functions to select the statistic, you're better off using `fixel2voxel` / the fixel toolbar.

We should however add an image like this and a brief description to the relevant wiki page.

**Comment by draffelt** [comment] 2015-06-22 08:09
If you don't have an underlying image to overlay fixels on, then it is good
to be able to use fixel image itself. So we don't want to restrict it.
Agreed that the 'gradient' that is seen due to the incremental pointer
offsets is a bit weird for new comers. One solution would be to detect the
*msf file, then display 1's in voxels with a fixel and 0's otherwise.

**Comment by Lestropie** [comment] 2015-06-22 08:18
> One solution would be to detect the *msf file, then display 1's in voxels with a fixel and 0's otherwise.

That doesn't actually solve either of the major problems:
* You'd have to compute that mask, store it in a scratch buffer, then branch all mrview operations involving the main image depending on whether it's the buffer or the scratch buffer that's open.
* I'm not convinced that showing a mask is any more / less informative; if anything, showing the pointers is preferable to me as it highlights to the user that they don't know what they're doing, and need to do some reading. If they see a mask, they may think the image is a mask and try to use it as such.

**Comment by thijsdhollander** [comment] 2015-06-22 08:18
Yep, I already started to figure that what I was looking at, are the incremental pointers.  Saying that currently, "nothing is broken per se"... that depends of course on the definition of broken.  If the behaviour is not intended/wanted, I'd call it "broken". :wink:  Displaying a statistic such as the sum is indeed `also` making some assumptions, so I definitely agree it's not the best solution as well.  I'd go for the binary display where fixels are present, as @draffelt suggests.

**Comment by thijsdhollander** [comment] 2015-06-22 08:57
@Lestropie : seems I posted almost simultaneously to you, so didn't take into account your last post here yet...

I understand your reasoning, but I do believe that we shouldn't bother the end user with the pointer values.  For them, it's really *never* going to be a sensible use case to visualise these pointer values.  The viewer is still a tool to cater for the users' needs, right (not for our own direct view on the internal structure of files)?  I don't even think they *should* be required to read up on how we happen to store the msf files.  If we need them to understand how msf files work internally to explain what they are seeing, then we are simply making things too complex for them, for the sake of our own internal design.  In case of the msf files in general, all the functionality (be it viewer, or commands) can actually be provided without opportunities for the user to make mistakes.  I understand it requires some ugly coding on the gui's code end, but as long as that code doesn't "invade" the API, there shouldn't really be a problem.  GUI code is never really that nice anyway, and MRtrix's, admittedly, is not an exception here (but that's not really a big issue if we are the only ones having to deal with that).
Even my "formal informatics training sense" is not itching here. :grin: This is simply the difference between the domain model ( https://en.wikipedia.org/wiki/Domain_model ) and the actual (class) design to solve the problem.  It's perfectly fine to serve the user with a completely separate logic (as long as it makes sense on its own) as compared to the one being used (internally) to implement the solution.  A correct domain model even explicitly *avoids* by all means to include abstract terminology/information that describes the solution: it's a blueprint that is *independent* from the language/platform/... or basically any technicalities that are part of 1 specific solution.

I still support @draffelt 's suggestion; to make things more obvious, we could show the (visually) "binary mask" where fixels are present, but still show *all* individual fixel values as the voxel information (i.e. no binary ones or zeros over there; to avoid really suggesting that the image is a binary mask).

Actually, when I first accidentally opened that msf file, it showed an axial slice somewhere in the middle of the brain.  At that position, the pointer values are so high that they differ relatively very little from each other.  Because the background is still zeros, the automatic min-max windowing made it look like a mask (I almost thought it did that on purpose, until I switched to coronal view...), but then combined with a not-so-obvious value.  Just scrolling through axial slices did not make anything clear either.

**Comment by jdtournier** [comment] 2015-06-22 09:41
OK, I can see how that might seem 'broken', but maybe I should mention some of the logic behind some of these decisions. Basically, from time to time I find people using one of my commands for a totally different purpose that it was designed for - something I hadn't anticipated, but then I'm surprised to find it 'just works' for whatever they're doing. So I've come to think that it's always best to avoid placing restrictions on how the software is to be used, just because it might not fit with our current view of what is 'right' - as long as the behaviour remains well-defined algorithmically. I see no real value in going out of our way to prevent users from doing something that is perfectly sensible as far as the code goes, even if it might cause some head-scratching when users stumble across these cases by mistake. I think most users are savvy enough to figure out why things might have gone funny when they inspects their inputs. But more importantly, it means the software could be used for purposes that we hadn't anticipated - and with no effort on our part. 

In this case, the only issue is that we're allowing users to (probably accidentally) look inside the internals of the sparse image format. Personally, I think that's a good thing. It means users can use existing functionality to debug or verify the output of the various sparse commands (for example, we can just ask then to load it in the viewer directly and tell us what they see). I can see users being a bit surprised to find that they can load these images at all, but most will just note that the data looks garbage and go use the correct tool. A few might wonder what it is they're looking at, and will look up the doc for the sparse format in the wiki, where these issues will be nicely documented (ahem). And who knows, a few of them might even get ideas for how they might be able to use this format for their own stuff...

One thing we could do is issue a warning when these images are used in the wrong context  (i.e. opened as a regular image). Hopefully, it'll be possible to do this for both command-line and GUI, and there genuinely will never be cases where we are intentionally opening a sparse image as a regular one (?). I'll look into how this could be implemented in the updated_syntax branch, I think this might be a useful feature. But I don't think I'd want to actively prevent anything beyond that...

**Comment by thijsdhollander** [comment] 2015-06-22 09:53
Ok, I can definitely live with a good warning for this case... :-)

(still it's a bit funny they can look inside the internals, but then don't get to see the (fixel) values in there that are probably more relevant to them :stuck_out_tongue_winking_eye: )

**Comment by jdtournier** [comment] 2015-06-22 09:56
True enough. But the alternative is simply to prevent them from opening the image that way, which would probably confuse novices just as much. At least with a warning, we can tell them to use the fixel tool instead...

**Comment by thijsdhollander** [comment] 2015-06-22 10:02
Yes, I agree.  @draffelt also has a point about the case where they would only have a fixel image.  They still need a main image to show the actual fixel overlay.  So strictly preventing is indeed not the best.

As a side note: it's probably also important that the wiki (or just any manual or basic tutorial) mentions quite clearly that a main image is needed for overlays to actually show.  Simply using the vector plot on its own shows nothing...

**Comment by Lestropie** [comment] 2015-06-22 11:11
> One thing we could do is issue a warning when these images are used in the wrong context (i.e. opened as a regular image)

Been a while since I wrote it, so not sure how easy/difficult this will be to do, and the updated syntax may change possibilities entirely. Can check for the `sparse_data_name` and `sparse_data_size` header fields. Probably a virtual function in the Buffer that's called in the constructor to look for those, and BufferSparse overloads with a requirement that they exist...?

> As a side note: it's probably also important that the wiki (or just any manual or basic tutorial) mentions quite clearly that a main image is needed for overlays to actually show. Simply using the vector plot on its own shows nothing...

Definitely; had a question about this today. Maybe in the FAQ?

**Comment by jdtournier** [comment] 2015-06-22 11:15
> Probably a virtual function in the Buffer that's called in the constructor to look for those, and BufferSparse overloads with a requirement that they exist...?

Yes, that's more or less what I had in mind...

**Comment by draffelt** [comment] 2015-08-14 22:33
I think this is ok to close this now...

**Closed by draffelt** 2015-08-14 22:33 UTC
Labels: gui

**Comment by thijsdhollander** [comment] 2015-08-17 02:22
:+1: Will probably be fixed inherently at some point.
