### ISSUE TITLE
labelsgmfix -force option not applied

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#892] opened 2017-01-26 01:02 UTC
Dear experts,

I am encountering error with `labelsgmfix -force`. When the output file already exists, the final `mrconvert` command of `labelsgmfix` script exits with error `file already exists`. Looking to the log, the final `mrconvert` is executed without `-force` option (despite the `lib.app.mrtrixForce` is used in code).

**Comment by Lestropie** [comment] 2017-01-27 05:51
Hi @ansk,

Good spot, thanks for the report. The issue is that variable `lib.app.mrtrixForce` isn't actually updated to set the `-force` option on any *MRtrix3* command calls unless a pre-existing file is detected by function [`lib.app.checkOutputFile()`](https://github.com/MRtrix3/mrtrix3/blob/master/scripts/lib/app.py#L108), at which point the user is given a warning that that particular output file already exists and will be overwritten. The issue is that `labelsgmfix` isn't actually calling that function at present. It will be fixed once I hit the merge button for #895.

Cheers
Rob

**Closed** 2017-01-31 07:27 UTC
