### ISSUE TITLE
Robust handling of Philips data w. trace image

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2172] opened 2020-09-15 12:47 UTC
As reappeared on [forum](https://community.mrtrix.org/t/dwi2response-error-iter0-fixel-peaks-mif/4010), but has apparently been observed many times.

If a volume is present with a null vector direction but a *b*-value equivalent to a valid shell, particularly if it is the last volume in the series, it's likely to be Philips data with a reconstructed trace-weighted image. Such a volume needs to be excluded from any A2SH transformation at least; possibly other components would need to detect & handle such data as well, someone would need to run a suite of commands to see what breaks and what doesn't.

**Comment by jdtournier** [comment] 2022-03-10 17:19
OK, after looking into this in more detail, prompted by [requests from the forum](https://community.mrtrix.org/t/dwipreproc-problem-dwipreproc-853/2887/6?u=jdtournier), I think we may have a solution. 

First off, I don't think we'll be able to keep these trace-weighted volumes in the data and handle them downstream, relying on the specific applications to detect and ignore them. The problem is that following the changes in #2015, the DW encoding table gets cleaned up and stored in a format that can be assumed ready for analysis; these trace-weighted volumes with encoding `[ 0 0 0 b ]` are indistinguishable from a _b_=0 that might have been acquired via modulation of the gradient amplitudes on systems that only allow for a single _b_-value - and will hence be immediately converted to actual _b_=0 volumes if _b_-value scaling is on (the default). The user will be a warning about it, but I don't expect many users to really look at this too closely. In short, I think these have to be kept separate from the actual measured DWI data or removed altogether. 

Having rummaged around these types of data a bit, it turns out there's a special Philips private DICOM entry `2001 1004 DiffusionDirection` which takes value `'O'` for regular orientational DWIs, and `'I'` for isotropically-weighted images. Only slight snag is that genuine _b_=0 images are also labelled `'I'`, so we need to be a bit more careful when stripping out the synthetic trace-weighted images. Basically, look for those labelled `'I'` with _b_>0.

Ideally, the best way to do this would be to split the series into the DWI data as measured, and the synthetic trace-weighted images, as separate outputs that the user can select. However, while technically possible, this would require a fairly drastic overhaul of the current approaches we use to do this (which is currently based solely on the `0008 0008 ImageType` entry). Notably, the backend assumes that there is one ImageType per file, and so isn't designed to allow a multi-frame image to be split - and yet, I have examples of Philips multiframe data with these trace-weighted images in it... 

In more detail: the current approach for DICOM handling uses an initial quick recursive scan through the folder to create an inventory of the data, then allowing the user to select which series they're interested in (if there's more than one), and finally do a more complete parse of the specific files selected. The problem is that the quick scan would require (i) a more complete scan to get all the information required for the split (including notably, the b-value, which can be stored in all kinds of places...), and (ii) quite an overhaul to allow a single multi-frame dataset to be split across multiple selectable series.  

A much simpler approach, and the one I've implemented in 5df4c98 as part of #2442, is to simply strip out the frames / images detected as isotropically-weighted (trace-weighted) after the user selection process, when the images / frames are being sorted and assembled into a complete series ready for use. Hopefully that will be acceptable for most users... 

In any case, I'll close this issue and refer everyone to #2442 for ongoing discussion...

**Closed by jdtournier** 2022-03-10 17:19 UTC
Labels: bug
