### ISSUE TITLE
ODF tool's sagittal preview is wrong

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#424] opened 2015-12-15 16:05 UTC
Ok, this suddenly came to mind; saw it just before I left for Belgium and didn't have the time to write up an issue or investigate further.  This was on updated_syntax before @Lestropie merged his branch that introduced dixel and tensor overlays in that tool.  Basically, when using the ODF preview "sub-tool", and looking at the image in sagittal orientation (locked to axes), the preview was in another orientation (which was also not the axial or coronal one, but something like upside-down or rotated 90 degrees in another orientation).  Don't know if it's still an issue, and if it's consistently reproducible in the way I just described though...

**Comment by jdtournier** [comment] 2015-12-16 12:52
I can't reproduce... Anyone having similar issues?

**Comment by thijsdhollander** [comment] 2016-01-06 01:57
Just pulled the current/latest version of the updated_syntax branch, and I still get the aforementioned issue.  Here's a few screenies (region shown is the splenium).  Axial and coronal view are fine, but the preview's orientation is wrong for the sagittal one.

Axial:
![screenshot from 2016-01-06 12 45 28](https://cloud.githubusercontent.com/assets/11952694/12132872/219f5ffc-b474-11e5-8a6d-85d3ca0261a7.png)

Coronal:
![screenshot from 2016-01-06 12 45 36](https://cloud.githubusercontent.com/assets/11952694/12132876/256399f0-b474-11e5-9b48-e6579cc1de44.png)

Sagittal:
![screenshot from 2016-01-06 12 45 44](https://cloud.githubusercontent.com/assets/11952694/12132879/281236f2-b474-11e5-8321-be10e19e0a72.png)

**Comment by jdtournier** [comment] 2016-01-06 09:40
OK, confirmed: sagittal is definitely not right. The other issue is that the ODF preview doesn't update the first time on a change of projection (i.e. pressing A, C or S) - only on the second key press...

**Comment by Lestropie** [comment] 2016-01-08 06:09
That should be the orientation sorted; with the delayed update, it seems to be calling the update function as it should, but the projection that the ODF preview window is accessing has itself not yet been updated to reflect the new orientation. But that's the same as the master branch. So gonna have to dig around in the guts a bit.

**Comment by jdtournier** [comment] 2016-03-23 16:57
@Lestropie, can we close this?

**Comment by Lestropie** [comment] 2016-03-23 22:48
The delayed update issue is still there (i.e. the preview window doesn't immediately rotate on a change of projection).

**Comment by Lestropie** [comment] 2016-03-30 06:13
... Well that wasn't much fun. Have a look at f9f58dd0 to see what was required to get around this one. Could probably do with a second set of eyes so that I don't merge a broken viewer to master...

**Comment by jdtournier** [comment] 2016-03-30 09:06
Whoa... Looks like there's about 4 commits' worth of changes in there! From a quick look at the commit description, it seems most of these changes are unrelated to the remaining issue? Which changes actually fixed the delayed update issue? Or were all these changes necessary to ensure the projection is up to date...?

A couple of other things: 

- for a while, I couldn't figure out the rationale behind _Volume mode now snaps to image axes rather than realspace axes_ - I presume this is to bring it in line with the other modes? I thought I'd disabled snap to image axes for this mode, since it makes no sense. Are you talking about what happens where the view is reset...?

- I was surprised to find the `Math::Versor` class was still there when I looked into it a few weeks ago. But then I figured the `Eigen::Quaternion` class probably wasn't normalised. But now that you've come up with the `Eigen::AngleAxis` class (well spotted!), do we need the `Math::Versor` class at all? It seems a perfect fit, I reckon we should ditch `Math::Versor` if at all possible, just to reduce the amount of code that needs to be maintained and documented... The only thing that might be problematic are the conversions to/from `GL::mat4` to `Eigen::Matrix4`, etc. But these could probably be handled using small inline converter functions. 

- I don't get the need for this complicated-sounding change: 

  _ODF preview sets its orientation by getting a transform vector from the orientation versor, rotating according to the current selected plane (just as is done when setting the projection matrices), and converting back to versor._

  I thought all rotations, etc were already in real space, so would never need to be modified like this. Why is this required?

**Comment by Lestropie** [comment] 2016-03-30 11:45
Yeah I was trying a lot of different things, and this is how it came out the other side.

The primary fix for the delayed update is:
`render_frame->set_rotation (window().get_current_mode()->get_current_projection()->modelview());`
to:
`render_frame->set_rotation (window().get_current_mode()->plane_adjusted_orientation());`

What was happening is as follows (gather 'round, kids). Hitting A/C/S signals `Window::set_plane()`, which just changes the value of `int Window::anatomical_plane`. This member only has an effect during `Mode::Base::adjust_projection_matrix()` when setting up the projection matrices: the 'actual' viewed orientation is the orientation stored in `Window::orientation`, modified by this function. However, when the ODF preview is drawn, what is returned by `window().get_current_mode()->get_current_projection()->modelview()` is _not yet updated_ based on the change in orientation - hence the ODF preview would be drawn based on the old orientation, until you hit the A/C/S key a second time (or do anything else) and it then sees the updated modelview matrix.

The implemented change bypasses having to wait for the modelview update, by generating a versor orientation that's directly modified by the updated anatomical plane selection. It's definitely not a unique solution, but it works.

> for a while, I couldn't figure out the rationale behind Volume mode now snaps to image axes rather than realspace axes - I presume this is to bring it in line with the other modes? I thought I'd disabled snap to image axes for this mode, since it makes no sense. Are you talking about what happens where the view is reset...?

Pretty much. As far as I could tell the functionality still works, you're just unlikely to not rotate your view for any period of time. But previously, e.g. going to volume render from slice mode would snap to realspace axes rather than image axes.

> I was surprised to find the Math::Versor class was still there when I looked into it a few weeks ago.

It got removed initially during the `updated_syntax` port, then re-implemented, mostly for that rotate-about-axis-by-angle functionality. But even without that it's still useful as a thin wrapper; e.g. it prevents write access to the raw data members and enforces normalization. I would prefer a better solution to the `GL::mat4` handling though.

> I thought all rotations, etc were already in real space, so would never need to be modified like this. Why is this required?

Pretty sure it's your code  :-P  Answer as above: the current value of `int Window::anatomical_plane` is _always_ taken into account when setting up the modelview matrix; even when the viewer is _not_ snapped to image axes. So the 'orientation' field is not trustworthy unless the value of `anatomical_plane` is taken into account.

**Comment by Lestropie** [comment] 2016-04-07 05:18
@jdtournier Got an opinion on whether to take this fix as-is, or whether we should more generally change how the camera orientation is tracked given the capability of plane switching?

(E.g. should the stored orientation always be faithful to the camera orientation, with changes in anatomical plane causing an instantaneous re-calculation of that orientation, rather than a delayed permutation of the modelview matrix in `Mode::Base::adjust_projection_matrix()`)

**Comment by jdtournier** [comment] 2016-04-11 12:06
OK, I had a look into this, since I was getting very confused why things weren't working. To cut a long story short, I think the only fix that was ever required was to call `update_preview()` in the `Tool::ODF::draw()` method - i.e. if the main window is ever updated, update the preview window too, and crucially make sure the update is invoked _after_ the main window update, so that the projection is up to date. 

This means we can get also get rid of the callbacks set up to handle the update of the preview window...  See pull request #531 - seems a much simpler fix that what's currently being suggested.

**Comment by Lestropie** [comment] 2016-04-12 02:05
OK, I must have over-engineered a solution because the preview update callback was executing before the main ODF tool. I must admit, on multiple occasions I looked at the end of `ODF::draw()` and wondered why `update_preview()` wasn't there... Much cleaner.

Given there were some other cosmetic changes I made in my `odf_preview_update` branch that weren't exclusively to fix this problem, I might merge my branch into yours but remove my hack fix of the actual problem.

It might also be worth documenting that `MRView::Window::orientation` does not take the selected anatomical plane into account (this only occurs in `Mode::Base::adjust_projection_matrix`, even if not locked to axes), and therefore that member is not a faithful representation of the current camera orientation.

**Comment by jdtournier** [comment] 2016-04-12 07:23
> Given there were some other cosmetic changes I made in my odf_preview_update branch that weren't exclusively to fix this problem, I might merge my branch into yours but remove my hack fix of the actual problem.

Sure, I'll take a look.

> It might also be worth documenting that MRView::Window::orientation does not take the selected anatomical plane into account (this only occurs in Mode::Base::adjust_projection_matrix, even if not locked to axes), and therefore that member is not a faithful representation of the current camera orientation.

Yes, good point. It might not be obvious. Basically the idea is that the `orientation()` field refers to the rotation of the coordinate system, and the `plane()` allows you to specify axial/sagittal/coronal orientation with respect to that. The reason is that there is a legitimate use case where you might want to reorient the image slightly (e.g. to align to the AC/PC line) or a lot (when the image transform is just totally wrong), so in this case the axial/sagittal/coronal still make anatomical sense. However, I agree that if the rotation is too extreme, these labels no longer make much sense. The trouble is it's impossible to detect when they no longer make sense, so we might as well allow this at all times.

The way it's intended to be used is that the `orientation()` and `plane()` combined define the projection via the appropriate `Projecton` class. From this point on, all queries about the actual transformation used in the render should be handled via this `Projection` class - there's a lot of convenience methods in `Projection` to help out there. So you get issues like this when the projection used is not up to date at the time of use, which is what was happening here. 

I'll document this when I have a minute...

**Comment by Lestropie** [comment] 2016-04-12 23:25
Delayed update solution rejected in favour of #531; `odf_preview_update` branch deleted and issue closed.

**Closed by Lestropie** 2016-04-12 23:25 UTC
Labels: bug, gui
