### ISSUE TITLE
Glitch in full screen mode on Mac OS X

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#270] opened 2015-06-17 14:20 UTC
Since mrview is under a lot of scrutiny lately, I thought I'd add this one as well...

I get the following minor (but aesthetically very unpleasing) glitch in mrview whenever I switch to full screen mode (regardless of whether I enter full screen mode through the mrview menu or through the title bar full screen button from MacOS X):
![mouse_off_menu_bar](https://cloud.githubusercontent.com/assets/5675416/8209101/6bd59536-150b-11e5-93cd-87d25d020ed0.png)

Whenever I hover the mouse on the Mac OS X menu bar on top, everything looks fine as below:
![mouse_on_menu_bar](https://cloud.githubusercontent.com/assets/5675416/8209095/67df7c4e-150b-11e5-839e-d3e1297537da.png)

But moving away the mouse cursor results in the glitch of the first screenshot again.

I am using qt 5.4.2 on yosemite.

Any idea what might cause this? Might just be a qt bug, but couldn't immediately find any similar issues on the qt forums.

**Comment by jdtournier** [comment] 2015-06-17 16:16
Yes, I've noticed this too, and always assumed it was a Qt bug. You'll also notice that after hiding the menubar (Cmd-M) and showing it again, it displays correctly. My guess is, the reason we have this problem is because MRView doesn't include a 'traditional' menu bar, we use the toolbar to hold both the menus _and_ buttons for commonly used actions (the mouse mode and lock to axis buttons). This was basically done to save some screen real estate - a bit like what modern GNOME apps look like. I wouldn't be surprised if Qt expected that menubar to be present, and screwed up the placement of the toolbar as a consequence. 

It would be nice to set up a minimal app with an empty frame and just the toolbar (as is done in MRView) and see whether this displays the issue. We could then file a bug report to Qt... assuming of course that the issue is with Qt rather than the specific way we use it.

**Comment by jdtournier** [comment] 2015-06-19 22:21
Just came across [this](http://doc.qt.io/qt-5/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop), might be relevant...

**Comment by jdtournier** [comment] 2015-07-03 11:19
Looks like this is fixed in Qt 5.5. Can you verify and close off if you can confirm?

**Comment by bjeurissen** [comment] 2015-07-03 11:29
Confirmed!

**Comment by jdtournier** [comment] 2015-07-03 11:30
:1

**Closed by jdtournier** 2015-07-03 11:30 UTC
Labels: bug, gui, help wanted
