### ISSUE TITLE
Getting error in dwi2response

### ISSUE THREAD

**Issue by MarcRamos** [MRtrix3/mrtrix3#337] opened 2015-09-01 10:39 UTC
Hi mrtrix3 developers,

I am using mrtrix3 to get the response file from a diffusion image. I am getting this error

dwi2response: [ .  ] optimising response function.. terminate called after throwing an instance of 'MR::Exception'
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborted (core dumped)

I did a backtrace and this is what it comes out:
dwi2response: [  . ] optimising response function.. [New Thread 0x7fffdd983700 (LWP 12398)]
[New Thread 0x7fffde184700 (LWP 12399)]
[New Thread 0x7fffde985700 (LWP 12400)]
[New Thread 0x7fffdf186700 (LWP 12401)]
terminate called after throwing an instance of 'terminate called recursively
MR::Exception'
[New Thread 0x7fffdd182700 (LWP 12402)]
terminate called recursively
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdf186700 (LWP 12401)]
0x00007ffff68a4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Is the first time I see this and I have been using this a lot. What can be the problem? The diffusion image looks fine, I can open it and the mask is matching in dimensions and space the diffusion image. I tried other functions with this image and is fine. Actually I got the response easily using mrtrix0.2 with the same files and then computed the fod with mrtrix3.

My machine has this specs:
Linux version 3.16.0-46-generic (buildd@lgw01-57) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015
8 vCPUs, 52 GB RAM

Thanks!
Marc.

**Comment by Lestropie** [comment] 2015-09-01 13:04
Well that's not good. I presume that log is from GDB but the command is terminating before you can get a proper backtrace on it? One thing to try is manually specifying lmax: start from 4 and work your way upwards. Also just confirm that you're using the most up-to-date code; there's been a couple of fixes to this command. Short of that, I'd need to get a copy of the problematic data in order to reproduce and start bug hunting proper: robert.smith@florey.edu.au

**Comment by Lestropie** [comment] 2015-09-02 00:52
OK Marc, thanks for sending me the data.

Running with the newest version of the software should provide you with this clue:

```
dwi2response__debug: [WARNING] directions are poorly distributed for lmax = 6 (condition number = 5.69077e+32)
dwi2response__debug: [WARNING] directions are poorly distributed for lmax = 4 (condition number = 4.23433e+16)
dwi2response__debug: [WARNING] reducing lmax to 2 to improve conditioning
dwi2response__debug: [ERROR] Cannot run dwi2response with lmax less than 4
```

What this is reporting is that although you have enough _DWI volumes_ to support an _lmax_=6 fit, the _distribution_ of those diffusion sensitisation gradient orientations is not good enough to support such a fit; in fact, it's not even good enough to support _lmax_=4.

Manual inspection of your gradient table shows that although you have 36 _b_=1000 DWIs, these are in fact 3 repeats of 12 directions; this is insufficient for an _lmax_=4 fit, which requires at least 15 _unique_ directions. Therefore you won't be able to estimate a response function from these data; though if you can get a response function from elsewhere you can probably run CSD with _lmax_=4 due to its super-resolution property.

Although the process used in MRtrix 0.2 for response function estimation may not report an error, and therefore be perceived as having 'worked', the process still internally requires a mapping from DWI data to SH, and this will be intrinsically very unstable; it's just that 0.2 is failing to report as such.

**Closed by Lestropie** 2015-09-02 00:52 UTC
Labels: bug
