### ISSUE TITLE
convert_bruker: miscalculation of number of gradient directions

### ISSUE THREAD

**Issue by dgrens** [MRtrix3/mrtrix3#2177] opened 2020-09-23 13:44 UTC
**Describe the bug**

When converting diffusion 2dseq file an inaccurate number of gradient direction is grabbed

**To Reproduce**

everytime

**Platform/Environment/Version**

Generic python script

**Advanced debugging information (if applicable)**

in line 137 we have : bvec = [ bvec[n:n+3] for n in range(0,len(**bval**),3) ]
and we should have instead : bvec = [ bvec[n:n+3] for n in range(0,len(**bvec**),3) ]

**Comment by jdtournier** [comment] 2020-09-23 14:28
Yes, that script is provided on a best-effort basis, but given I rarely deal with Bruker data, it's not getting much attention... 

That change seems entirely appropriate, and frankly I'm surprised this hasn't caused more issues so far. If I understand this right, this means that the script should have always resulted in shorter `bvecs` arrays than actually acquired, by a factor of 3 - and caused an immediate mismatch between bvals & bvecs in subsequent analysis? I'm surprised the `zip()` call directly afterwards doesn't fail - but then [the docs](https://docs.python.org/3.3/library/functions.html#zip) do state it'll simply stop when the shortest array is exhausted.

Looking through the history for this file, the commit that broke things would presumably have been 39124acb, which was released as part of 3.0_RC3 - so quite a while ago... Surprising that no-one has raised this till now!

Based on this, it might be time to add in some regression testing for this script... But then I'd need to get hold of more Bruker data than I currently have, and set up an offline set of tests (might be too much data to hold online). Assistance would be appreciated here...

**Comment by jdtournier** [comment] 2020-09-23 14:33
@dgrens: could you confirm the fix in the `fix_convert_bruker` branch (#2178) sorts out the issue? It's a straight application of your suggestion...

**Comment by dgrens** [comment] 2020-09-24 10:01
> Yes, that script is provided on a best-effort basis, but given I rarely deal with Bruker data, it's not getting much attention...
> 
> That change seems entirely appropriate, and frankly I'm surprised this hasn't caused more issues so far. If I understand this right, this means that the script should have always resulted in shorter `bvecs` arrays than actually acquired, by a factor of 3 - and caused an immediate mismatch between bvals & bvecs in subsequent analysis? I'm surprised the `zip()` call directly afterwards doesn't fail - but then [the docs](https://docs.python.org/3.3/library/functions.html#zip) do state it'll simply stop when the shortest array is exhausted.
> 
> Looking through the history for this file, the commit that broke things would presumably have been [39124ac](https://github.com/MRtrix3/mrtrix3/commit/39124acbc166f7dea0852146085485c422ed5bbf), which was released as part of 3.0_RC3 - so quite a while ago... Surprising that no-one has raised this till now!
> 
> Based on this, it might be time to add in some regression testing for this script... But then I'd need to get hold of more Bruker data than I currently have, and set up an offline set of tests (might be too much data to hold online). Assistance would be appreciated here...

We don't have many Bruker datas pertinent to diffusion at the moment in my facility (WIP). And I'm just a MR physicist with a nearly decent programming background (regression testing is a brand new concept for me). If you want some assistance to tackle Bruker issues I can try to help but don't expect to much from my coding abilities.

**Comment by jdtournier** [comment] 2020-09-24 10:50
Thanks, not a problem. The main thing I'd be looking for is data - preferably acquired on different Bruker systems with different acquisition parameters - along with curated and known-good versions of the same data converted to a standard format (preferably our own `.mif` format). If we have a bank of such data, we can run conversions to `.mif` on a regular basis (ideally every time something changes in the code, but that's typically too expensive) and verify that the data matches the known-good versions, which would allow us to catch regressions (hence the name). This might have caught the change the caused the problem here, for example. 

But to do this, I'd need someone to collate these data, convert them using our script, verify that the conversion worked correctly each time, and store the original and converted data somewhere I can access them. I can take care of writing the testing backend itself (I already have a similar test suite for DICOM data), but the data collation and curation is where I'd need help... 

The other outstanding issue is that we don't currently extract the orientation of the image volume. So we'll get that wrong for any tilted or non-axial acquisition. I'd like to fix that, but again that requires quite a bit of test data, all with different orientations to ensure we're not missing some strange edge cases, along with ground truth solutions. And it's that last point that requires a bit more effort and knowledge of how the data were in fact acquired.

If anyone is keen to help out with this, that would be great!

**Comment by dgrens** [comment] 2020-09-24 13:00
ok, now I  see
We don't have much Bruker diffusion data right know but we can easily
produce some typical ones (on different Bruker software version) and push
them where you want or even leave you a download access somewhere (girder).
For the question of subject positioning within Bruker multiverse, you're
touching the decades recurring pain in the neck issue of Bruker subject
orientation
We are also quite concerned by this point and I think that I could spend
some time working to solve it (acquiring data and programming).

**Comment by Lestropie** [comment] 2020-09-30 07:55
Closing due to merging #2178; other improvements to the `convert_bruker` script should ideally be redirected to a new dedicated Issue, and linked to the initial discussion here.

**Closed by Lestropie** 2020-09-30 07:55 UTC
Labels: bug
