### ISSUE TITLE
mrconvert -bvalue_scaling

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#178] opened 2015-03-08 21:43 UTC
I am confused with the bvalue_scaling option that comes with mrconvert, e.g. as in:
mrconvert -bvalue_scaling true DICOM dwi.mif

This does not result in a dwi.mif file with scaled b-values.

I vaguely remember that the idea of the bvalue_scaling parameter was to not touch the data, but to use it to calculate the actual bvalues to be used in the processing. However, for a command like mrconvert, I kind of expect it to generate a mif file with scaled b-values.

So I think, either

1) the b-values should be scaled in the resulting mif file

2) the option should be removed from the mrconvert command

Where I would strongly prefer option 1) as option 2) makes processing multi-shell data a pain (i.e. having to remember to set the bvalue_scaling command for all DWI processing commands, instead of just once when importing from dicom).

**Comment by bjeurissen** [comment] 2015-03-09 10:26
E.g. the following patch would result in option 1):

```
diff --git a/cmd/mrconvert.cpp b/cmd/mrconvert.cpp
old mode 100644
new mode 100755
index 5d9c07f..bd8e77b
--- a/cmd/mrconvert.cpp
+++ b/cmd/mrconvert.cpp
@@ -101,7 +101,9 @@ inline std::vector<int> set_header (Image::Header& header, const InfoType& input
   header.intensity_offset() = 0.0;
   header.intensity_scale() = 1.0;

-  if (get_options ("grad").size() || get_options ("fslgrad").size())
+  if (get_options ("bvalue_scaling").size())
+    header.DW_scheme() = DWI::get_valid_DW_scheme<float> (header);
+  else if (get_options ("grad").size() || get_options ("fslgrad").size())
     header.DW_scheme() = DWI::get_DW_scheme<float> (header);

   Options opt = get_options ("axes");
````

What do you guys think?

**Comment by jdtournier** [comment] 2015-03-09 10:48
Yes, the problem is that this option is part of the GradImportOptions group, which is really designed for apps that _use_ the gradients, whereas mrconvert really only provides that option to insert (and now export) the gradient table, without modification. We had a bunch of discussion about this around issues #48 and #60. One option that we discussed (offline, unfortunately) was modifying the GradImportOptions to allow using only the subset of options that are _strictly_ related to import, or the full set for apps that actually also need to interpret the gradient table. We would also modify `mrinfo` with an option to process the gradient table with `DWI::get_valid_DW_scheme()`, so the `-dwgrad`, `-export_grad_mrtrix` and `-export_grad_fsl` would all provide the gradient table _as applications would interpret it_, rather than as it was stored in the original data. I'm not sure how you're exporting the gradient table, but assuming it was using `mrinfo`, this would IMO be the best course of action.

In principle, what you're suggested would work just fine for what _you_ want to do, but there's two reasons I'm not keen on the idea:

- most of the changes that happened around the bvalue scaling option were basically to ensure that the DW scheme never gets modified from its original version - as it was read from the DICOM. If I'd done this from the start, there's a bunch of buggy datasets I would have spotted much earlier than I did (the direction vector was totally messed up, but looked fine after normalisation). If we pass the gradient table through the `-bvalue_scaling` option, that implies that this information will be modified, making it difficult to inspect later on (since it will look like the scheme was acquired as-is, potentially hiding bugs in the acquisition itself if users assume the DW information is a direct match to the DICOM information.

- as it stands, calling `DWI::get_valid_DW_scheme()` will result in an exception if the image dimensions don't match with the scheme (it will also normalise the directions, and hence modify the scheme, with the caveats above). Not a problem 99% of the time, but it's a limitation that I'm not sure is necessary - there is nothing wrong with an image other than a raw DWI containing a DW gradient table; you couldn't analyse it as a raw DWI (it'll raise an exception when you try), but if for example all you want to do is document what DW scheme was used for that image, you should be able to.

The other thing I'm not sure about is why you need to supply the `-bvalue_scaling true` option to your pipeline - it's on by default. Unless you're talking about processing them outside MRtrix, in which case the modification to `mrinfo` that I mentioned earlier should fit the bill. What do you reckon?

**Comment by bjeurissen** [comment] 2015-03-09 12:06
I think mrinfo with an option to use get_valid_DW_scheme() would indeed be great.

Right now, the eddy command in the revpe_distcorr script is crashing on multi-shell data, because it can't make sense of the DW data with the unscaled b-values.  The combination of the mrinfo fix with bvalue_scaling being on by default for all commands (which is already the case), should probably result in a painless multi-shell experience.

**Comment by jdtournier** [comment] 2015-03-09 12:11
Cool. Should be trivial with the changes I made to `mrinfo` recently. Just need an extra option to request validation of DW gradient table, and adding a check for that option at line 188 to use `DWI::get_valid_DW_scheme()` rather than `DWI::get_DW_scheme()` if that option is supplied...

Feel free to have a go - probably won't have time today...

**Comment by bjeurissen** [comment] 2015-03-09 12:31
OK. Just looking at the mrinfo manual, I was wondering whether the current bvalue_scaling import option is meaningful?

**Comment by jdtournier** [comment] 2015-03-09 13:01
Yes, good point. At the very least, it should state what the default is... If you can think of a way to better explain exactly what is going on in a succinct way, feel free to give it a shot. I thought it was already quite long enough as it was... Maybe we should expand on this in the wiki - along with the FSL bvecs/bvals handling issues, which will also need proper explanation, given issue #141...

**Comment by bjeurissen** [comment] 2015-03-09 13:04
Should the bvalue_scaling import option not be removed from those commands?

**Comment by jdtournier** [comment] 2015-03-09 14:15
Well, it should be removed from mrconvert. I don't think there's any other command that'll allow gradient table import without interpreting it...?

**Comment by jdtournier** [comment] 2015-03-09 14:16
You'll definitely want it for `mrinfo`, otherwise you'll get the original unscaled table...

**Comment by jdtournier** [comment] 2015-05-07 09:13
@bjeurissen - can we close this...?

**Comment by bjeurissen** [comment] 2015-07-15 15:03
`mrinfo -shells -bvalue_scaling true -validate dwi_ap.mif.gz`

produces:

`0 933.333 1866.67 2800`

while 

`mrinfo -shells -validate dwi_ap.mif.gz` 

produces:

`0 2800`

so it seems the default of -bvalue_scaling true is ignored for the mrinfo -shells command.

Also, should it not be possible to extract shells correctly using the mrinfo command without the -validate option?

**Comment by jdtournier** [comment] 2015-07-15 15:28
OK, first issue should be fixed with 7c99401 - please check that it works as expected.

> Also, should it not be possible to extract shells correctly using the mrinfo command without the -validate option?

This one is a bit trickier. The validate option is explicitly about enforcing the interpretation of the gradient table as would happen in diffusion applications. The main issue really is that the documentation for the `-bvalue_scaling` option indicates that this scaling will be done by default - which it would in any other context. For `mrinfo` however, I think I'd rather keep the behaviour consistent, in that only when `-validate` is supplied would any modification of the gradient table be performed - anything else would give you information derived from the raw gradient table as stored in the header. The simplest thing is probably to override the default `-bvalue_scaling` option so that its documentation is actually correct in this context. Thankfully that should be pretty easy - I'll have a go now. 

Other option is invert the sense of `-validate` - i.e. have a `-novalidate` or similar option that prevents any interpretation of the gradient table. Maybe `-raw_dwgrad` would be a better name? That way it would be possible to inspect the raw gradient table for inconsistencies, but the default behaviour would be more in line with expectations...?

**Comment by bjeurissen** [comment] 2015-07-15 15:56
I think the second option is less likely to confuse people and at the same time keeps the option of obtaining the raw gradient table, so I like it!

**Comment by jdtournier** [comment] 2015-07-15 16:02
OK, option `-raw_dwgrad` added with commit 2426fea - see if that works as expected...

**Comment by jdtournier** [comment] 2015-12-10 21:42
Guess we can close this one...?

**Comment by bjeurissen** [comment] 2015-12-11 19:02
Yes!

**Closed** 2015-12-11 19:02 UTC
Labels: enhancement
