### ISSUE TITLE
fsl.py (5ttgen) does not pick up combined first segmentation file in fsl v5.09

### ISSUE THREAD

**Issue by AlistairPerry** [MRtrix3/mrtrix3#1068] opened 2017-07-22 06:57 UTC
I'm running `5ttgen fsl` on fsl version 5.09 (with eddy patch http://fsl.fmrib.ox.ac.uk/fsldownloads/patches/eddy-patch-fsl-5.0.9/centos6/eddy_openmp).

I'm running into the following error:

```
File "/software/mrtrix3/mrtrix3-20170707/lib/mrtrix3/_5ttgen/fsl.py", line 181, in execute
    app.error('FSL FIRST has failed; not all structures were segmented successfully (check ' + path.toTemp('first.logs', False) + ')')
NameError: global name 'path' is not defined
```

`fsl.py` on line 174 looks for file `first_all_none_firstseg.nii.gz` in the temp 5tt directory.

With the above `fsl `version, however, the output filename of the combined first segmentation is `first_all_fast_firstseg.nii.gz`

Would it be more appropriate for this line to look for filenames matching the string *firstseg.nii.gz?

**Comment by Lestropie** [comment] 2017-07-24 06:33
Hey Alistair, thanks for the report.

> `NameError: global name 'path' is not defined`

That's a missing `from mrtrix3 import path` call; it should have given you a nicely-formatted terminal message...

> With the above fslversion, however, the output filename of the combined first segmentation is `first_all_fast_firstseg.nii.gz`

OK, various thoughts:

- I suspect different FSL versions are using different default settings for the boundary correction (see [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FIRST/UserGuide), `run_first_all` "output" bullet). Seems there is a manual control over what is done here using the `-m` option; however they claim their default is "auto", which uses different settings for different structures, yet this is not being reflected in the name of this combined image...

- I'm pretty sure the `run_first_all` script has an error in it: It seems to be setting the name of the output combined image based on the boundary correction method of *the last structure in the list*, rather than the overall setting (see "`methname=$btype ;`"; should be based on "`$bmeth`")... So explicitly using `-m auto` is unlikely to solve the issue.

- The boundary correction method *appears* to be image-based, and does not manipulate the surface mesh representations in any way. Therefore, given `5ttgen fsl` ignores FIRST's image outputs and only accesses the mesh files, using "`run_first_all -m none`" may be the easiest solution to this particular issue, and will avoid some unnecessary computations.

You can try number 3 if you want; I'll need to wait until I'm on a Linux box to play around.

**Comment by Lestropie** [comment] 2017-07-25 02:21
Yep, I was right:

- `run_first_all -s L_Caud,L_Thal -i T1.nii -o test1` produces `test1_all_none_firstseg.nii`

- `run_first_all -s L_Thal,L_Caud -i T1.nii -o test2` produces `test2_all_fast_firstseg.nii`

@AlistairPerry: Don't suppose you're using the `-sgm_amyg_hipp` option? That'll alter which structure name appears last in the "`-s`" option list; and if the boundary correction method is different between it and the structure that is normally at the end of this list in the `5ttgen fsl` call (which it is), that will correspondingly alter the name of this output file.

I've also confirmed that the boundary correction method has no influence on the surface meshes, only the output images. Therefore disabling boundary correction in `5ttgen fsl` is the easiest solution.

**Comment by AlistairPerry** [comment] 2017-07-26 02:04
Hey @Lestropie,

Sorry have been indisposed in bed the last few days.

> I'm pretty sure the run_first_all script has an error in it: It seems to be setting the name of the output combined image based on the boundary correction method of the last structure in the list, 

> Yep, I was right:
> 
> run_first_all -s L_Caud,L_Thal -i T1.nii -o test1 produces test1_all_none_firstseg.nii
> 
> run_first_all -s L_Thal,L_Caud -i T1.nii -o test2 produces test2_all_fast_firstseg.nii

Ok, this makes sense, thanks for debugging this!


> @AlistairPerry: Don't suppose you're using the -sgm_amyg_hipp option?


I am, with the parent command being:

`5ttgen fsl T1betFSmasked.nii.gz -nocrop -premasked -sgm_amyg_hipp 5TTFSmasked.nii -nthreads $ncpus -force -tempdir . -nocleanup`


Which invokes:

```
run_first_all -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal,L_Amyg,R_Amyg,L_Hipp,R_Hipp -i 
T1.nii -o first -b
```


So I gather the `-m none` option to `5ttgen ` will be added as a pull request?

**Comment by Lestropie** [comment] 2017-07-26 02:29
> So I gather the `-m none` option to `5ttgen` will be added as a pull request?

Yep; you can see the link to #1070 just above your comment on this page. In the description of that pull request I make reference to this issue, and hence GitHub automatically adds a link to that pull request within the timeline of this issue. It will even automatically close this issue once the pull request is merged.

**Closed** 2017-08-02 01:04 UTC
Labels: bug, scripts
