### ISSUE TITLE
mrview volume navigation crash in dev

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1640] opened 2019-07-17 00:16 UTC
On second thought, it might be better to create an issue anyway, as it's otherwise quite hard to keep track of comments on a closed pull request... So this particular issue is described [here](https://github.com/MRtrix3/mrtrix3/pull/1638#issuecomment-511734061) and [here](https://github.com/MRtrix3/mrtrix3/pull/1638#issuecomment-511737901) a bit further.

**Comment by maxpietsch** [comment] 2019-07-17 09:42
I can't reproduce this on macos. I followed [both scenarios](https://github.com/MRtrix3/mrtrix3/pull/1638#issuecomment-511734061) using the "Index:" to change the volume. For the right/left keys to work, I have to open a popup window after opening the view tool (due to #1641) and after that, I also do not observe the segfault or group index change on changing the volume.

My image is 96 x 128 x 128 x 30, Qt 5.12.0, latest dev (c5c7f9c).

**Comment by jdtournier** [comment] 2019-07-17 14:24
OK, I can reproduce. I'll investigate...

**Comment by jdtournier** [comment] 2019-07-17 14:52
Thanks for reporting. I'll close this, we can discuss any further issues in #1642.

**Closed by jdtournier** 2019-07-17 14:52 UTC
